### ISSUE TITLE
Physical exams step not displaying instantly after Medical history step

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#115]
**Environment**

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

**Describe the bug**
Complete Medical history step in a way that should make appear specific questions in Physical exams step.
Go to Physical exams step -> See error, you can't see those specific question instantly
-> To see them, you have to respond to a general Physical exams question first.

**Expected behavior**
Additional question of consultation should appear instantly arriving at Physical exams step

**Medical Case Info (Example)**

### Registration
Birth date : 3 May 2019

### Complaint Categories
All no

### Basic Measurements
20kg, child doesn't feel hot, Everything else: no

### Medial History
Cough: Yes, Everything else: No, Negative, Empty (when possible)

### Physical Exams
See error, 'Respiratory rate (breaths/min)' is not there.
Respond to a general question to make it appear

**Smartphone (please complete the following information):**
 - Device: Lenovo
 - Android version 10

**Comment by quentingirard** [comment]
Can't reproduce, could you retry with the latest APK ?
