### ISSUE TITLE
"Administer bronchodilator" unreachable following "Reactive airway disease" diagram

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#117]
**Environment**

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test
Reactive arway disease : https://liwi.wavelab.top/algorithms/1/versions/1/diagnoses/4/diagram#

**Describe the bug**
Following a path "Administer bronchodilator" should appear, but it doesn't
-> Issue looks related to "Blood oxygen saturation (%)".
-> Hypothesis: when entering a value in "Blood oxygen saturation (%)" it s like it stays empty.

**Expected behavior**
"Administer bronchodilator" should appear

**Medical Case Info (Example)**

### Registration
Birth date : 3 May 2019

### Complaint Categories
All no

### Basic Measurements
20kg, child doesn't feel hot, Everything else: no

### Medial History
Cough: Yes, Everything else: No, Negative, Empty (when possible)

### Physical Exams
Chest indrawing: Yes, Wheezing: Yes, Resp rate: Not feasible, Visible resp rate: Normal,  Blood oxygen saturation: 95, Everything else: No, Negative, Empty (when possible) 

### Assessments
"Administer bronchodilator" should be there
(but instead it's "Wheezing: Attempt trail of bronchodilator", it's like resp distress is always set to no, even with blood oxygen = 95 should be set to Yes)

**Smartphone (please complete the following information):**
 - Device: Lenovo
 - Android version 10

**Comment by frescoal** [comment]
According to the diagram (https://liwi.wavelab.top/questions_sequences/58/diagram) the Blood oxygen sat should be below 90 so, when I set it to 89 "Administer bronchodilator" is shown
if you are using another path let me know
