### ISSUE TITLE
Too much variables in "QUESTIONS" section

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#122]
## Environment

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

## Describe the bug
Too much variables in "QUESTIONS" section of the "Summary" of a "CLOSED" patient.

## Expected behavior
Take into account juste the variables for which have an answer.

##Smartphone
 - Device: Lenovo
 - Android version 10

**Comment by alanvonlanthen** [comment]
@frescoal validé. On doit ne voir que les questions répondues, sinon, cette vue est malheureusement inutilisable
