### ISSUE TITLE
When clicking the undo button of the tablet ("◁"), sometimes it leaves the app.

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#123]
## Environment

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

## Describe the bug
When clicking the undo button of the tablet, sometimes it leaves the app.
Click the "Hambourger" at the top left:
1) Click "SCAN QR CODE", then click the undo in tablet -> it leaves the app, instead of come back to the "Hambourger" open menu
2) Same as 1) when clinking on "CONSULTATIONS"
3) Same as 1) when clicking on "PATIENT LIST"
4) Same as 1) when clicking on "CONSENT FILES"
5) Same as 1) when clicking on "SETTINGS"
6) Same as 1) when clicking on "ABOUT"
7) Same as 1) when clicking on "SYNCHRONIZE"

##Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by quentingirard** [comment]
What is expected ?

**Comment by jouz56k** [comment]
Come back to the "Hambourger" open menu

**Comment by jouz56k** [comment]
Looks fixed

**Comment by alanvonlanthen** [comment]
Expected: 
* if keyboard open, the BACK button closes the keyboard
* if pop-up/pop-in/menu displayed, the BACK button closes the window/layer/menu
* as a general rule, the BACK button returns to the parent form
* if the BACK button is pressed from the homepage, prompt an OK/cancel warning message "Do you really want to leave the app?" (quit on OK or BACK)
