### ISSUE TITLE
Gray out the "no compatible options" + rename "no safe option" in "Formulations" step

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#124]
## Environment

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

## Describe the bug
If quick fix, gray out the formulation with "No compatible option" in it.
rename "no safe option"
And make impossible to select
@Rainer request

## Screenshots
![fdfdg](https://user-images.githubusercontent.com/55558015/124489178-03584b00-ddb1-11eb-9ec9-cd8c937f9ad9.jpeg)

## Medical Case Info
Link to diagram: https://liwi.wavelab.top/algorithms/1/versions/1/diagnoses/3/diagram#

### Registration
Birth date : 3 May 2019

### Complaint Categories
All no

### Basic Measurements
Weight: 20kg, Child doesn't feel hot, Everything else: Not feasible

### Medial History
Cough: Yes, Everything else: No, Negative, Not feasible, Empty

### Physical Exams
Chest indrawing: Yes, Everything else: No, Negative, Not feasible, Empty

### Assessments
Nothing

### Final diagnoses
-> Agree with Bacterial pneumonia
-> Is Amoxicillin available? No
-> Is Azithrmycin available? Yes
-> Agree with Azithromycin po
-> Select Formulations to see the situation

##Smartphone (please complete the following information):
 - Device: Lenovo,
 - Android version 10

**Comment by alanvonlanthen** [comment]
@frescoal not validated (not specific to the refactoring). @jouz56k will create an new story in Jira (for discussion on the best way to implement)
