### ISSUE TITLE
type/delete/retype/redelete bug

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#129]
## Environment

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

## Describe the bug
Research bar of consultations doesn't work properly
When tipping and deleting writing on the research bar of consultations
-> sometimes research bar is empty and our cases doesn't appear.

## Expected behaviour
 type/delete/retype/redelete should make appear correct patients taking into account what is currently typed in the research bar

## Screenshots
![pic1](https://user-images.githubusercontent.com/55558015/124570546-4a911b00-de47-11eb-9cb3-d2cf0a646cb9.jpeg)
![pic2](https://user-images.githubusercontent.com/55558015/124570551-4bc24800-de47-11eb-86e1-ab731ea19689.jpeg)

##Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by alanvonlanthen** [comment]
@jouz56k to add video to demonstrate the type/delete/retype/redelete bug (all lines disappear whilst the filter is actually empty)

**Comment by frescoal** [comment]
@cini9 Check avec @jouz56k  pour type/delete/retype/redelete bug

**Comment by cini9** [comment]
@jouz56k Je comprend pas le bug ici. Qu'est qu'on attend comme comportement ?

**Comment by jouz56k** [comment]
Link for the video on Slack -> https://slack-files.com/TUV1329CL-F027G47DSTZ-d0a203f9e3

**Comment by cini9** [comment]
@jouz56k Could not reproduce this bug on my emulator. Try again with the new apk and if the problem persists I'll have another look.

**Comment by jouz56k** [comment]
@cini9 this was reproduced again with App version 1.0.1

**Comment by quentingirard** [comment]
I think it's a Lenovo issue, I don't have it with the Samsung Galaxy Tab A. Could you try with a Samsung tablette ? @frescoal will try with a Lenovo next week

**Comment by jouz56k** [comment]
@quentingirard @frescoal @cini9 
Reproduced with Samsung Galaxy Tab -> To reproduce
I have a more specific scenario
1. Write two letters
2. Just before it starts to search, delete the two letter 
3. See error
There is like a timing gap that makes the research bug

**Comment by jouz56k** [comment]
As it s hard to reproduce, we close this one and maybe we will reopen in in the future.
We keep it in mind in PH.
