### ISSUE TITLE
Important: Weight for height issue

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#138]
## Environment

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

## Describe the bug
Type something in Current Weight (XX.X kg) *
-> Then observe Weight for height, it has a value, but there is no Height Entered
Remark: Besides that, entering values in Height -> Weight for height works well and display correct values

## Expected behavior
Weight for height should be Empty when there is no Height info

## Screenshots
![Screenshot_2021-07-08-10-27-27-409](https://user-images.githubusercontent.com/55558015/124891221-1188b000-dfd9-11eb-9944-4f23638f3b1e.jpeg)
![Screenshot_2021-07-08-10-28-59-880](https://user-images.githubusercontent.com/55558015/124891227-12b9dd00-dfd9-11eb-9e9b-24e2d06acaa5.jpeg)

### Registration
Birth date : 2020 February

### Complaint Categories
All no

### Basic Measurements
Type some thing in weight
-> See error Weight-for-Height has a value, but Height is still empty

##Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by quentingirard** [comment]
Can't reproduce, , weight for height is empty if I set only value in "Current Weight"

**Comment by jouz56k** [comment]
> Can't reproduce, , weight for height is empty if I set only value in "Current Weight"

Reproduced with Samsung 
BOD = 5 May 2018
-> Let Height "Empty" + Type something in Current Height => Weight for height = 3

**Comment by quentingirard** [comment]
Please provide all questions and answered
