### ISSUE TITLE
"LEAVE MEDICALE CASE" crash

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#139]
## Environment

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

## Describe the bug
- Create a consutation A
- Leave consultation A via the "LEAVE MEDICALE CASE"
- Go back to A or create a patient B
- Make sure to go back with A or B for at least one stage (by pressing prev, the side menu, or via the "Hamburger" consultation view) -> Crash

## Screenshots
![Screenshot_2021-07-09-09-36-21-919](https://user-images.githubusercontent.com/55558015/125041667-4bb98680-e099-11eb-90bd-66649380ec35.jpeg)

##Smartphone
 - Device: Lenovo, Samsung
 - Android version 9, 10

**Comment by quentingirard** [comment]
Can't reproduce actually, need more investigation
