### ISSUE TITLE
Important : MUAC z-scores doesn't display correct values

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#141]
## Environment

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

## Describe the bug
Looks that MUAC doesn't calculate properly, or maybe you have wrong tables.

## Expected behavior
A boy with 24 Months with MUAC 15 should display a z-score of 0 (currently it displays -1)
For this same boy MUAC = 17 should give us a z-score = 1 (currently it displays 0)
-> See OMS table : Arm circumference-for-age BOYS 3 months to 5 years (z-scores)
https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/arm-circumference-for-age/boys-simplified-field-tables-arm-circumference-for-age-3-months-to-5-years-(z-scores).pdf?sfvrsn=f509fd30_2

## Screenshots
![Screenshot_2021-07-08-11-38-35-567](https://user-images.githubusercontent.com/55558015/124900435-57497680-dfe1-11eb-879f-f1e813e7aac9.jpeg)

### Registration
Birth date (Estimated) : 24 Months

### Complaint Categories
All no

### Basic Measurements
MUAC = 15 => MUAC z-score = -1
-> Error

##Smartphone
 - Device: Lenovo
 - Android version 10

**Comment by frescoal** [comment]
Check sur l'ancienne app au lieu de regarder avec les table de l'OMS Rainer nous a fait faire des arrondi spéciaux

**Comment by jouz56k** [comment]
Dans l'ancienne app, pour MUAC: 15, ça affiche aussi -1, je ne sais pas ce que Rainer a décidé, mais ça ne correspond pas avec les tables de l'OMS.

**Comment by alanvonlanthen** [comment]
no entry point for 24 months in the ref table, this is why it behaves as though the child is 60 months old) => @jouz56k to see if table can be extended

**Comment by jouz56k** [comment]
So this one can be closed, a specific Jira story will be created when tables extended.
I am currently extending them from WHO tables and a PH story has been created:
**Tables for MUAC-for-age z-scores doesn't exist for age <60 Months**
-> https://dynamic-project.proofhub.com/bapplite/#app/todos/project-4532906095/list-134322977173/task-193777026128
