### ISSUE TITLE
Display issue for the patient list filter

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#151]
## Environment

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

## Describe the bug
See picture self-explanatory

## To Reproduce
1. Go to Patient list
2. Click the red filter icon
3. See error

## Screenshots
![Screenshot_2021-07-15-10-22-16-468](https://user-images.githubusercontent.com/55558015/125754752-ac9e9fa4-eb2a-49f7-9491-4ebb214c6e65.jpeg)

##Smartphone
 - Device: Lenovo
 - Android version 10

**Comment by cini9** [comment]
@jouz56k I can't reproduce this issue. Can you please try again with the latest apk ?
