### ISSUE TITLE
Diagnoses button on medal-c doesn't do anything

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#157]
## Environment

https://liwi-test.wavelab.top/

## Describe the bug
Diagnoses button doesn't do anything
-> See picture self-explainatory

## Screenshots
![rert](https://user-images.githubusercontent.com/55558015/125452324-81b52276-a840-4035-9ea2-f8d0b62a0009.PNG)

**Comment by frescoal** [comment]
Wrong repo => https://github.com/Wavemind/liwi-backend/
