### ISSUE TITLE
Create a new consultation for an existing patient should keep same BoD (true or estimated)

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#166]
## Environment

https://liwi-test.wavelab.top/
ePOCT+_TIMCI_SN_V0.0
SN Testing Health Facility TIMCI (Standalone)

## Describe the request
When creating a consultation for an existing patient,
It takes into account his First name, Last name, Sex, but no BoD

## Expected behavior
It should also take into account his BoD (true or estimated)

## Screenshots
![Screenshot_2021-07-16-10-44-50-426](https://user-images.githubusercontent.com/55558015/125920646-ac34a27d-aa5c-4275-a660-9fa1e568f5f7.jpeg)

##Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by jouz56k** [comment]
Looks this one, after doing process with a clear data and empty cache

**Comment by quentingirard** [comment]
Next time close the issue
