### ISSUE TITLE
Consultations view should display DoB

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#171]
## Environment

https://liwi-test.wavelab.top/
ePOCT+_TIMCI_SN_V0.0
SN Testing Health Facility TIMCI (Standalone)

## Describe the bug
Cultations view should display DoB

## To Reproduce
See pictures self-explainatory

## Expected behavior
DoB should be display

## Screenshots
![Screenshot_2021-07-16-13-28-14-410](https://user-images.githubusercontent.com/55558015/125941090-acd3d165-879a-4f25-b30a-e9800e5cf109.jpeg)
![image](https://user-images.githubusercontent.com/55558015/125941040-d5806891-2c46-48c4-a104-35929733b6e7.png)

##Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by frescoal** [comment]
Done it's not possible to set Differents font inside of a header
