### ISSUE TITLE
Regression : Keyboard is not anymore numerical

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#176]
## Environment

https://liwi-test.wavelab.top/
ePOCT+_TIMCI_SN_V0.0
SN Testing Health Facility TIMCI (Standalone)

## Describe the bug
Sometimes Keyboard is not anymore numerical
It happens sometimes, I don't have a specific scenario for now.

## To Reproduce
1. Go to Basic measurements
2. Tap on the empty box of current weight
3. See error, keyboard is not anymore numerical

## Expected behavior
Keyboard should be numerical as before

## Screenshots
![Screenshot_2021-07-16-16-38-07-313](https://user-images.githubusercontent.com/55558015/125965263-bf6c03f6-8521-4f14-b5b1-ebeff3f8ec76.jpeg)

##Smartphone
 - Device: Lenovo
 - Android version 10

**Comment by cini9** [comment]
@jouz56k Nous n'avons pas réussi a reproduire ce bug. Est-ce que tu as essayé de fermer le keyboard et de la rouvrir ?

**Comment by jouz56k** [comment]
@cini9 This issue is still present in Lenovo, don't if it s related to the device or App,
Je ne vois pas ce que tu veux dire par fermer le keyboard et la rouvrir?

**Comment by cini9** [comment]
@jouz56k Quel est le model des tablettes Lenovo que vous utilisez ? Et la version du OS Android ?

**Comment by jouz56k** [comment]
@cini9 
Lenovo TB-8505F
Android version 10
-> Mais on dirait que c'est ok maintenant, ça arrive aléatoirement en fait, je n'ai pas réussi à mettre le doigt sur un pattern encore

**Comment by cini9** [comment]
@jouz56k Si le clavier reste ouvert parce que t'arrives depuis une autre page, ca n'a peut etre pas la possibilité de rafraichir le clavier. Test en fermant le clavier (en cliquant en dehors du champs) et en rouvrant le clavier (en cliquant dans le champs)

**Comment by jouz56k** [comment]
D'acc, je testerai ta méthode si ça rebug encore, pour l'instant c'est denouveau ok

**Comment by jouz56k** [comment]
@cini9 
Le clavier rebug, j'ai testé selon ta méthode de cliquer sur un champ à l'extérieur du clavier et de réouvrir le clavier, il n'est toujours pas numérique (sur Lenovo).
Remarque 1: Un médecin a rapporté le même problème avec sa Lenovo.
Remarque 2: Cela m'est arrivé de pouvoir régler le problème en allant dans les settings via le petite engrenage (see Screenshot) sur le clavier et en revenant dans l'App. Actuellement même en faisant ça, ça ne règle pas le problème.
Screenshot
![Screenshot_2021-07-29-10-48-52-143](https://user-images.githubusercontent.com/55558015/127462182-f07acffb-6939-4b4d-a296-a542c6d3df73.jpeg)
