### ISSUE TITLE
UX detail of display when coming back to Diagnoses stage

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#181]
## Environment

https://liwi-test.wavelab.top/
ePOCT+_TIMCI_SN_V0.0
SN Testing Health Facility TIMCI (Standalone)

## Describe the bug
Display bug when coming back to Diagnoses stage
-> See picture

## To Reproduce
1. Add a new patient
2. Go to Diagnoses stage
3. Go home via the "hambourger" menu
4. Press the patient just created
5. See error

## Expected behavior
The weird "line" shoudn't display
Note: It appears also in the "Black" mode of the App.

## Screenshots
![Screenshot_2021-07-19-10-18-39-662](https://user-images.githubusercontent.com/55558015/126127413-7eeb562a-c460-4427-8cc8-a8e81c45b7b7.jpeg)

##Smartphone
 - Device: Lenovo
 - OS: Android version 10

**Comment by jouz56k** [comment]
Happens also when coming back from home to 1st Assessments step

**Comment by cini9** [comment]
@jouz56k For the 1st Assessment stage, is it any step in particular ? Or all of them ?

**Comment by jouz56k** [comment]
@cini9 We can drop this one for now, it is not high priority, I keep it in mind for future consideration in Proof Hub
