### ISSUE TITLE
Uppercase to labels of answers of questions

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#183]
**Environment**
Server : https://liwi-test.wavelab.top/
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0

**Describe the bug**
UX visual detail
-> When clicking in "Owner of primary phone number*", labels of answers should start with an uppercase
-> To keep the consistency related to labels of answers to questions (They start with a uppercase most of the time)
Note: Samething for  "Owner of second phone number"

**To Reproduce**
1. Go to "Registration step"
2. Click on "Owner of primary phone number*"
3. See error

**Expected behavior**
Labels of answers should start with uppercase
 
**Screenshot**
![Screenshot_2021-07-19-13-13-42-956](https://user-images.githubusercontent.com/55558015/126152740-bd276ec2-a850-4936-a272-ac6c028993bf.jpeg)

**Smartphone**
- Device: Lenovo
- Android version 10

**Comment by frescoal** [comment]
C'est géré sur Medal-C je te laisse update et close la issue
