### ISSUE TITLE
When having to enter the pin code for the first -> The pin code view lag

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#186]
**Describe the bug**
When having to enter the pin code for the first time (After selecting "Staff" name) -> The pin code view lag

**Smartphone**
 - Device: Lenovo
 - Android version 10

**Additional context**
If a video is needed -> request me on Slack (José Paz)

**Comment by frescoal** [comment]
Because we are loading the algorithm from Medal-C won't fix
