### ISSUE TITLE
Issues when creating a New staff member

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#187]
**Description of the bug**
When entering in the App for the first time, or when logout, we can choose our Staff member name or Create a new one,
-> 2 issues
1: There is a suggestion when clicking in the First name and Last name box -> it's not pertinent (to remove)
2: After saving it, if we logout, we can't see our new staff member (it hasn't been taken into account) -> It s not visible also in medal-c
Note: You can observe the issue related to "Dark mode switcher" Git-#185

**Expected behaviour**
1: Drop the suggestion
2. Make a real save of the new staff member (have to be added in medal-c to to see it)

**Screenshot**
![Screenshot_2021-07-19-14-08-11-957](https://user-images.githubusercontent.com/55558015/126158613-d95c8d1c-cdaf-42fc-8f7f-22cfb750553a.jpeg)

**Comment by frescoal** [comment]
The suggestion is relate to the OS can't do much
It's not supposed to create a clinician in medal-C it's just a temporary user

**Comment by jouz56k** [comment]
Okay, maybe we should rename "New staff member" by "New temporary user" -> Will see with clin-it team
And can you at least drop the suggestion? @frescoal

**Comment by frescoal** [comment]
Alan choose the label I let you check with him
As said above, can't drop the suggestions.

**Comment by jouz56k** [comment]
Okay @frescoal sorry didn't read well your message
