### ISSUE TITLE
Add a "little" medAL-reader icon

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#196]
Add a "little" medAL-reader icon in the android view of the tablet switching from one app to another
-> See picture self explanatory

**Screenshot**
![Screenshot_2021-07-20-09-54-33-722](https://user-images.githubusercontent.com/55558015/126284498-0596edf3-8aeb-40b5-814e-63b7ae7a964b.jpeg)

**Comment by jouz56k** [comment]
Noticed that for Samsung it is ok, but not for Lenovo

**Comment by cini9** [comment]
@jouz56k Is the samsung icon round ?

**Comment by jouz56k** [comment]
Yes in Lenovo
-> See screenshot
![Screenshot_2021-07-20-10-50-31-672](https://user-images.githubusercontent.com/55558015/126291956-e6b1c775-f633-4536-89d1-8ebf29a61e33.jpeg)

**Comment by cini9** [comment]
@jouz56k I've updated the icons to remove the white background around the logo. You should get them in the next apk. For the missing icon when switching apps, could you try to reboot the tablet and see if an icon appears ?

**Comment by jouz56k** [comment]
I just rebooted the tablet Lenovo, and now there is the "little" icon -> well done!
And yes good idea to remove the white I'm glad to see that

**Comment by cini9** [comment]
Cool, it seems like it just needs a reboot to refresh the icon set in the tablet. You may need to do the same with the next apk.

**Comment by jouz56k** [comment]
@cini9 
In Samsung looks very good now
But for Lenovo there is still white (I rebooted the tablet, and unistall reinstall App) -> See pictures
![Screenshot_2021-07-21-13-40-56-596](https://user-images.githubusercontent.com/55558015/126483239-27477deb-a57f-4027-9622-bb4f06f3d67a.jpeg)
![Screenshot_2021-07-21-13-40-27-907](https://user-images.githubusercontent.com/55558015/126483244-3d48f085-f097-49f7-87d0-bf596b5d0803.jpeg)

**Comment by cini9** [comment]
What model is the Lenovo tablet ? And what Android OS version is it running ?

**Comment by jouz56k** [comment]
@cini9
Lenovo TB-8505F
Android version 10

**Comment by cini9** [comment]
Are there any apps on the tablet that have full app icons (ie without the white border) ?

**Comment by jouz56k** [comment]
Some of them Yes,
but as you can see in picture "Dolby Audio" is also problematic
![Screenshot_2021-07-21-16-26-55-873](https://user-images.githubusercontent.com/55558015/126505769-e08cfcb8-6703-4016-98a7-351bdf27f57b.jpeg)

**Comment by frescoal** [comment]
C'est probablement la surcouche Lenovo qui fait ça on peut pas faire grand chose à mon avis Tous les icons qui ne sont pas natives ont ce tour blanc

**Comment by jouz56k** [comment]
Okay, so if we can set it again like it was first it will look better (Currently it smaller than it was first)
-> See picture
![126291956-e6b1c775-f633-4536-89d1-8ebf29a61e33](https://user-images.githubusercontent.com/55558015/126517803-e4daaf73-e0af-43eb-8b68-4597cd6eb586.jpg)
