### ISSUE TITLE
Miss aligned diagnoses ("i" info vs. not "i" info)

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#198]
**Describe the bug**
See picture self explanatory
- Miss aligned reproduced with Lenovo and Samsung
- Moreover missing separation for diagnoses without "i" info button for JUST Samsung

Note: I can give a scenario if needed

**Screenshot**
![tempFileForShare_20210720-101317](https://user-images.githubusercontent.com/55558015/126291077-8117ce40-e284-433d-8123-03d36d1d6022.jpg)

**Comment by cini9** [comment]
@jouz56k Can't reproduce this one. Can you give me the scenario ?

**Comment by jouz56k** [comment]
Scenario
BoD -> 4 June 2017
CC -> All no
Weight -> 20, Child doesn't feel hot
MedH: Diff breathing -> Yes, Possibility foreign object in airway -> Yes, Everything else -> No, Negative
PhE: Visible respiratory rate -> Visibly fast, Everything else -> Absent, No, Not feasible
Go to Final diagnoses -> See bug
The "|" happened just with Samsung, the missalignement with Samsung and Lenovo
![tempFileForShare_20210720-121657](https://user-images.githubusercontent.com/55558015/126308145-225da834-63d4-4652-a5bf-656b214fa9b1.jpg)

**Comment by cini9** [comment]
J'arrive toujours pas a reproduire. Il faut qu'on test avec une tablette je pense

**Comment by jouz56k** [comment]
Looks much better now the Fina
