### ISSUE TITLE
Scan QR code issue

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#201]
**Describe the bug**
Add a new patient from "Home"
-> Click the "Hambourger" menu -> Click Scan QR code (-> EXIT, DON'T SAVE)
-> See error: QR code scanner doesn't take into account the scanned QR code

Moreover when pressing undo button it leaves the App

Samsung

**Comment by frescoal** [comment]
Cannot reproduce + Add a new patient from "Home" is only available for test and will be removed in production

Couldn't reproduce the undo button either

**Comment by jouz56k** [comment]
@frescoal this one should be fixed
Reproduced using only Scan QR button in Lenovo
1. From home Scan a QR
2. From Registration, go to Scan QR code in "hambourger" menu -> "leave consultation" -> "exit, don't save"
3. See error -> QR code doesn't scan
Moreover pressing undo -> It leaves (as described in first scenario)
