### ISSUE TITLE
Patient list missing closed status

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#203]
## Describe the bug
Patient list missing closed status

## To Reproduce
1. From home Add a new patient consultation
2. Go through the consultation until close it
3. In home you see the consultation closed -> Ok
4. But in Patient list view you see nothing -> See screenshot

## Expected behavior
Closed or something like that should be displayed

## Screenshots
![tempFileForShare_20210720-121134](https://user-images.githubusercontent.com/55558015/126308501-fc6ff427-bc06-471b-8fef-2d1f2458feb1.jpg)

##Smartphone
 - Device: Samsung

**Comment by jouz56k** [comment]
It is nice now we can see the message "No active consultations"
-> As there is just one current consultation per patient
-> Better drop the final s in the comment -> "No active consultation"
@cini9

**Comment by frescoal** [comment]
Zero is plural in english 
https://www.thoughtco.com/zero-plural-grammar-1692622

**Comment by jouz56k** [comment]
@frescoal thank you nice to know
