### ISSUE TITLE
To improve UX : do something cleaner with the LEAVE APP view

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#206]
See picture self-explanatory
![tempFileForShare_20210720-143609](https://user-images.githubusercontent.com/55558015/126325198-b185ce74-aaac-4416-8f4c-d4397fc78bad.jpg)

**Comment by frescoal** [comment]
Won't fix 
https://app.zeplin.io/project/60acaf631291d0263f90afdb/screen/60acc8fd0e3a5d4edb25fd75
