### ISSUE TITLE
Warning message for Age in days in TIMCI issue

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#218]
## Describe the bug
The warning message for ages in TIMCI is in French and doesn't cover the bottom cut-off

## Expected behavior
Use same message used in Dyn studies with 5 instead of 15.

## Screenshot
![erwer](https://user-images.githubusercontent.com/55558015/126469981-9e33bd5c-6686-463f-b60a-06bf8acad7a7.jpg)

**Comment by frescoal** [comment]
C'est géré dans Medal-C Je te laisse faire les modif

**Comment by jouz56k** [comment]
Okay merci pour l'info @frescoal
