### ISSUE TITLE
Weird bug pressing "< PREV"

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#219]
**Describe the bug**
When pressing "< PREV" -> look at the "NEXT" button -> It is clicked
There is an interaction with "NEXT" when pressing "< PREV"

Samsung, Lenovo

**Comment by cini9** [comment]
@jouz56k When the PREV button is pressed, the NEXT button is disabled (not clicked). That is the interaction that you are seeing. It is so that the calculations can be run without somebody pressing the NEXT button half way through

**Comment by jouz56k** [comment]
Je vois ce que tu veux dire @cini9, mais à priori on peut penser que ça bug, surtout qu'en pressant sur "Next" il se grise de la même façon -> Perso je désactiverais ce "grisage" (après c'est low priority)

**Comment by jouz56k** [comment]
I close this one also -> Low priority for now
