### ISSUE TITLE
Regression : Variables seem crushed against the left

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#220]
## Describe the bug
Text of variables is crushed against the left
See picture self-explanatory
It wasn't like that before, this can be related to the closed issues : Git-#198, Git-#205

## To do
Restore previous display, without affecting Git-#198, Git-#205 (fixed now)

## Screenshots
![Screenshot_2021-07-21-14-31-45-526](https://user-images.githubusercontent.com/55558015/126489583-ebd58465-5e1c-4bcf-b89f-fa0451fd01a6.jpeg)

##Smartphone
 - Device: Lenovo
 - Android version 10

**Comment by cini9** [comment]
@frescoal This might be related to the Layout.fill that you added to the QuestionInfoButton. Not sure tho

**Comment by cini9** [comment]
I still can't reproduce the original issue [#198](https://github.com/Wavemind/liwi-medal-reader/issues/198) but I've taken a stab at correcting it without @frescoal solution. Please test and let me know
