### ISSUE TITLE
Critical: Diagnoses stage issue

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#224]
## Environment
Server : https://liwi-test.wavelab.top/
TIMCI SN

## Describe the bug
Agree with a diagnosis **D** in Diagnoses stage
Then go to summary -> You can see **D**
Now come back and change answers of the consultation in order to not reach **D**
Go to summary -> See error -> **D** is still there

Note: I can attach a scenario if needed

##Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by cini9** [comment]
@jouz56k Please provide the scenario

**Comment by jouz56k** [comment]
TIMCI SN
Estimated BoD : 2 Years
CC : All no
BM : Weight : 20, Child doesn't feel hot
MedH : Dif. breathing : Yes, Everything else: No, Negative, Not feasible
PhE : Visible respiratory rate : Visibly fast, Everything else: No, Not feasible, Absent
-> Agree with Pneumonia -> Go to summary -> See Pneumonia
-> Come back to PhE -> Set Visible respiratory rate : Visibly normal
-> You don't have anymore Pneumonia in Final diagnoses stage -> Go to summary -> See error Pneumonia is still there
Note: see picture There is also something hide at the right
![Screenshot_2021-07-21-16-50-57-288](https://user-images.githubusercontent.com/55558015/126509753-9152c38a-61c3-42ae-8dd7-0b04d03496e5.jpeg)
