### ISSUE TITLE
Behaviour when switching to estimated DOB not ideal

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#228]
## Environment

Server : https://liwi-test.wavelab.top
HF : 124 RW Bweyeye Standalone
Algorithm : ePOCT+_DYN_RW_Intervention_V0.1

## Describe the bug
It is unclear what is asked to the user when switching to estimated DOB.
The label remains "Date of Birth" and there is no hint that the user needs to select day/month/year from the dropdown menu.

## To Reproduce
1. Open the app
2. Unlock it
3. Create a case
4. Enter date of birth as estimated

## Expected behavior
Ideally when switching to estimated and selecting a parameter from the drop down (days/months/years) the label should change from "date of birth" to "Enter estimated <selected parameter>"

Months should be preselected from the dropdown as it is probably the most common situation (medical suggestion).

## Smartphone (please complete the following information):
 - Device: Blackview BV9900Pro
 - OS: Android 9

**Comment by frescoal** [comment]
Ok for the preselected Month value for the label needs to be discussed with Alan as it's a new feature
