### ISSUE TITLE
CRITICAL : weight-for-age z-scores not recalculating

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#229]
**Environment**
Server : https://liwi-test.wavelab.top
HF : 149 SN testing HF Standalone
Algorithm : ePOCT+_Timci_SN_v0.0

**Describe the bug**
Change date of birth by 2 years -> Weight-for-age z-scores should recalculate following changes

**To Reproduce**
1. Go to BM -> Add a Weight 
2. Come back to Registration -> Change BoD
3. Come back to BM -> See error -> z-scores hasn't been recalculated

**Expected behavior**
z-scores should recalculate when entering in BM

**Note**
Genre -> Female
BoD -> 4 March 2019 and Current weight -> 10, should give a wfa z-score = -1
BoD -> 4 March 2017 and Current weight -> 10, should give a wfa z-score = -3
https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/weight-for-age/girls-simplified-field-tables---weight-for-age-birth-to-5-years-(z-scores).pdf?sfvrsn=6606c085_4

**Comment by frescoal** [comment]
L'algorithme a pas été pensé pour que la date de naissance change. 

Je vais adapter le code
