### ISSUE TITLE
CRITICAL : CC conditioning not working - TIMCI Senegal

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#231]
## Environment
Server : https://liwi-test.wavelab.top
HF : TIMCI Test Senegal (149)

## Describe the bug
Questions appearing that should only appear based on CC selection e.g.
Ear problem / runny nose / mouth problem / sore throat / neck lump should only appear if ENT selected
Abdo pain should only appear if GI selected
Eye problem etc only if eye selected
Significant exposure to fire or smoke only if accident / trauma etc

### Registration
DoB 09/04/2019
No recent visit / new (self-referral)

### Complaint Categories
CCs: Fever

### Basic Measurements
Weight 10kg
Height 87cm
MUAC 112 mm
Temp 37.4

### Medial History
History: No to all danger signs
Fever: Yes - 3 days duration.
 
## Note
Retested with same dob, with normal nutrition status (13 kg, 95cm MUAC 130mm, temp 36.8) and no history of fever - questions still appearing.

**Comment by frescoal** [comment]
Most of the question are instancied here !

**Comment by jouz56k** [comment]
So do you think it is exclusively a logical issue from algos in medAL-c, and not IT ?
