### ISSUE TITLE
Dilution & Dispensing instructions missing/incorrect for parenteral drugs

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#232]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
IM/IV dilution instructions coming after dispensing instructions – when should come before (should be à Dilution guidance than Dispensing guidance)

Ampicillin IM/IV
Oxacillin IM/IV First Dose
Paracetemol IV 7.5mg/kg/6h

Missing IM dilution instruction

Ampicillin IM/IV
Oxacillin IM/IV First Dose
Oddly enough – it shows for Paracetemol, but not the other 2 above drugs

## Steps to reproduce
Add any parenteral drug and check to see if same issues occurs – does not see it happen with all parenteral drugs.  

## Expected behavior
Instructions should shows as follows:

IM dilution
IV dilution
IM dispense
IV dispense

### Registration
Male
DOB 24 Dec 2020

### Complaint Categories
GI

### Basic Measurements
7 kg
65 cm
140 mm
T° 37°

### Medial History
Diarrhea – Yes
Duration of Diarrhea – 10
Everything else NO

### Physical Exams
All unremarkable (absent, no, or normal)

### Assessments
N/A

### Final diagnoses
Acute Diarrhea, Low risk of HIV, Screening & Prevention – agree

### Medecines
Acute Diarrhea

Drugs: Zinc Sulfate 20mg – ERRO: Duration missing; all other components present/correct
Mmgt: ERROR - Feeding counselling shown for every age despite being conditioned in medAL-C to be age specific
Low risk of HIV

Drug: none- correct
Mngt: ERROR- Incorrect Mngt suggested – 8981: Refer mother for HIV counselling and testing – despite test being negative à this should not appear
Screening & Prevention

Drug – ERROR - Mebendazole PO (deworming) not suggested
Mngt: all correct

### NOTE: I also manually added 11 drugs for sake of checking all formulation types
**Tablet** – Amox-Clav 500mg tablet – 250mg q12h - correct
**Capsule** – Fluconazole 1 capsule = 50mg q24h - correct
**Syrup** – Azithromycin 125mg/5ml = 70mg q24h (2.8ml of 125/5ml) - correct
**Suspension** – Phenoxymehtylpenicillin (Penicillin V) po 125/5ml suspension – 315mg (12.6ml) q12h – correct
**Suppository** – 50mg rectal artesunate (Weight <10kg) (medication form not managed) = q24h – ERROR – “medication form not managed” despite it being in creator
**Solution** – paracetamol 500mg/50ml = 53mg (5.3ml) q6h - correct
**Powder for Injection** – Oxacillin 1000mg/6ml  = 183.3mg (1.1ml) q6h – ERROR: should be 175mg (1.05ml) q6h (ie. 100mgx7kg/4 times per day = 175mg)
**Cream** – Clotrimazole 1or 2% cream – 2 applications q12h - correct
**Ointment** – Benzyl Benzoate Emulsion 25%:  50ml – ERROR: missing frequency/day – should be every 24hr
**Inhaler** – Salbulatmol 100mcg inhaler – 2 inhaler q6h - correct
**Dispersible Tablet** – Amoxicillin 125mg tablet – 125mg q12h - correct

## Additional context
App version: 1.0.3

**Comment by jouz56k** [comment]
Pour celle-ci si on pouvait ordonner selon l'expected behavior, ca serait pas mal apres pour ce qui est de la missing info pas réussi à reproduire

**Comment by frescoal** [comment]
Je sais pas de quoi on parle.
Dans quel écran je suis sensé retrouvé IM/IV dilution instructions coming after dispensing instructions ?

**Comment by jouz56k** [comment]
Dans le Summary du Diagnoses stage

**Comment by alanvonlanthen** [comment]
Sur medAL-reader, dans la vue "Diagnoses / Summary", pour les médicaments injectables, 

![232_medAL-R](https://user-images.githubusercontent.com/2785940/127113472-70a6910d-99af-4533-9670-38510fff5251.png)

1. Afficher d'abord les instructions de dilution (cf. A dans medAL-creator ci-dessous), puis les instructions d'administration (B dans medAL-creator ci-dessous). 

2. Ne pas fixer ces champs en hauteur : il faut qu'ils s'adaptent à la longeur du contenu dans medAL-C (qui peut être assez long). Si pas possible, permettre un scroll

![232_medAL-C](https://user-images.githubusercontent.com/2785940/127113459-8c4bb4d8-e83c-4191-bd73-dccc20d9ca5c.png)

**Comment by frescoal** [comment]
@cini9 Ln 62 and 70  from Liquid.js

**Comment by cini9** [comment]
@ManuBarchich You need to do point 2 of Alan's comments

**Comment by alanvonlanthen** [comment]
TIMCI TZ - diarrhea - acute diarrhea - duration still missing in medAL-reader for zinc sulfate 10mg (though present in instance in medAL-c) (screenshots tomorrow)
