### ISSUE TITLE
Duration of Zinc Sulfate 20mg not appearing

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#233]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
Zinc Sulfate should be prescribed x10d as per medAL-Creator - but is says "for undefined days" in Reader

## To Reproduce
Follow steps outlined to get to Acute Diarrhea Dx
Go to Summary to see error

## Expected behavior
Zinc Sulfate 20mg q24h x10d

### Registration
Sex -> Male
DoB -> 24 December 2020 -> (~7 Months)

### Complaint Categories
Gastrointestinal (abdominal problems, vomiting) -> Yes
Everyting else -> No

### Basic Measurements
Weight -> 7 kg
Height -> 65 cm
MUAC -> 140 mm
Temp -> 37°

### Medial History
Diarrhea -> Yes
Duration of Diarrhea -> 10
HIV mother - negative -> Negative
Everything else -> No, Empty

### Physical Exams
Everything -> Absent, Normal, No

### Assessments
Nothing

### Final diagnoses
Acute diarrhea, Low risk of HIV, Screening and Prevention -> Agree

### Healthcare questions
Everything -> Yes

### Medicines
**Acute Diarrhea**
Zinc sulfate 20 mg -> Agree

### Formulations
Zinc sulfate 20 mg -> 20mg dispersible tablet: 1 tablet(s)

### Summary
**Acute Diarrhea**
See error -> undefined day(s) instead of 10 day(s)

## Smartphone
- Lenovo
- Android version 10

**Comment by jouz56k** [comment]
@frescoal 
Story updated

**Comment by alanvonlanthen** [comment]
still not OK
("during undefined days" though duration set in instance of drug in medAL-c) 
![image](https://user-images.githubusercontent.com/2785940/127197227-7a0e9313-4134-4916-8771-dfb3c5d4b89a.png)
(TIMCI TZ, HF 79, diag acute diarrhea)

**Comment by alanvonlanthen** [comment]
@jouz56k all good for me (TIMCI TZ zinc sulfate mg scenario), works well, you can close the story 

![image](https://user-images.githubusercontent.com/2785940/127303133-63351a11-eda3-4e2f-bcb5-4bada5632102.png)
