### ISSUE TITLE
Diagnosis Hierarchy

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#235]
## Environment
Server :  https://liwi-test.wavelab.top/]
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0
 
## Describe the bug
In medicines step diagnoses are not shown according to final diagnosis hierarchy
Although likely problem in all environments / algorithms

**Comment by jouz56k** [comment]
Je reste à dispo si besoin de plus d'info sur la hiérarchie

**Comment by jouz56k** [comment]
@frescoal 
Each diagnosis is ranked from 1-10 based on the severity. On the summary screen the diagnoses are in order of severity (highest to lowest). The goal would be to use this same order for the "Medicines" step.

**Comment by alanvonlanthen** [comment]
order still not good, see below (tested in TEST, HF 79m, algo TIMCI TZ): 
![image](https://user-images.githubusercontent.com/2785940/127199861-d8d2de8b-accb-476d-846f-8b936bba547e.png)

**Comment by cini9** [comment]
@jouz56k @alanvonlanthen The original bug report stated that order needed to be changed in the Medicines step. Could you guys please make sure you are aligned on what the requirements are before creating the issue reports ? Does the order also need to be by level of urgency in the Final Diagnoses step ?

**Comment by alanvonlanthen** [comment]
Hi Sinan,

Sorry about the confusion, I guess we assumed that was the case already.

Long story short, any list of final diagnoses displayed in medAL-reader
needs to be ordered by descending level of urgency.

Also, any list of managements displayed in medAL-reader needs to be ordered
by descending level of urgency.

On a last note, I of course understand that it would be ideal for you if we
had a chance to review all the implications of the stories we submit and
make sure we haven't forgotten any loose ends. I hope you understand that
we are not in an ideal world. Just like you, we are doing our best in a
high-pressure / low-resource environment, and mistakes are bound to happen.
Thanks for your support on this :)

Cheers!

++

Alan

**Comment by cini9** [comment]
@alanvonlanthen no worries. We make do with what we have :) Do the additional diagnoses also need be ordered by level_of_urgency ?

**Comment by alanvonlanthen** [comment]
Nope, this would make them super difficult to find and pick by the end user. 
So, indeed. Not "all" lists of final diagnoses need to be ordered by urgency... I just added yet another layer of confusion whilst actually trying to clarify things, sorry about that :'(

**Comment by cini9** [comment]
Haha no its ok. Makes sense. Thanks for the reply !
