### ISSUE TITLE
Wrong calculation for Oxacillin IM/IV first dose when added as an additional Drug

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#237]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
**Algo recommend**
-> "Give: 183.333mg..." (this value could come from 1000/6=183.333 "wrong calculation")
-> "1,1ml per admninistration..." (as 183.333 is wrong -> 1000mg/6ml => 183.333/1.1ml -> 1.1ml is wrong)
**Should be** 
-> "Give: 175mg..." (100mgx7kg/4 times per day = 175mg)
-> "1,05ml per admninistration..." (1000mg/6ml => 175mg/1.05ml)

## To Reproduce
Follow the scenario below

## Expected behavior
175mg (1.05ml) every 6 hours

## Medical Case Info
Link to diagram of the drug : https://liwi-test.wavelab.top/algorithms/7/drugs/10054/edit

### Registration
Sex -> Male
DoB -> 24 December 2020 -> (~7 Months)

### Complaint Categories
Gastrointestinal (abdominal problems, vomiting) -> Yes
Everyting else -> No

### Basic Measurements
Weight -> 7 kg
Height -> 65 cm
MUAC -> 140 mm
Temp -> 37°

### Medial History
Diarrhea -> Yes
Duration of Diarrhea -> 10
HIV mother - negative -> Negative
Everything else -> No, Empty

### Physical Exams
Everything -> Absent, Normal, No

### Assessments
Nothing

### Final diagnoses
Acute diarrhea -> Agree
Low risk of HIV, Screening and Prevention -> Disagree

### Healthcare questions
Nothing

### Medicines
**Acute Diarrhea**
Zinc sulfate 20 mg -> Disagree
Select additional drugs -> Oxacillin IM/IV first dose

### Formulations
Oxacillin IM/IV first dose -> 1000mg/6ml powder for injection...

### Summary
**Acute Diarrhea**
See error 
-> Should be "Give: 175mg..." (100mgx7kg/4 times per day = 175mg)
-> Should be "1,05ml per admninistration..." (1000mg/6ml => 175mg/1.05ml)

## Smartphone
- Lenovo
- Android version 10

**Comment by jouz56k** [comment]
@frescoal 
Updated story

**Comment by frescoal** [comment]
On avait définit qu'on affichait les valeurs numérique à une décimale.
(Le bug vient de la)
On va corrigé les calculs mais l'affichage sera faux on aura 

175mg et 1.1ml (au lieu de  1.05)

Est ce qu'on laisse 1 décimale ou on met 2 ?

**Comment by alanvonlanthen** [comment]
Couac de communication : ni José ni Lisa n'étaient dans les discussions sur l'arrondi au dixième, d'où la proposition de 1.05. Mais tu as raison, on a bien décidé ça. Du coup, c'est bien 1.1 qu'on veut et non 1.05. 
Merci :)

**Comment by jouz56k** [comment]
@frescoal 
Same result as before 183.33333 instead of 175.

Consider the following formulas to obtain correct dosing values:

**("Min dose mg/kg/day" + "Max dose mg/kg/day") / 2 x "Patient weight" / "Number of administrations per day" = mg dosing**

So: **(100+100) / 2 x 7 / 4  = 175**  ⇔  **100 x 7 / 4  = 175**.

**_round_(mg dosing x Total drug formulation volume (ml) / Concentration (mg in dose)) = ml dosing**

So: **175 x 6 / 1000 = 1.05**  ⇒  **_round_(1.05) = 1.1**.

Screenshot
![retretert](https://user-images.githubusercontent.com/55558015/127294263-1f44490a-0a6b-49c7-9a73-682701777151.PNG)
medAL-c URL: https://liwi-test.wavelab.top/algorithms/7/drugs/10054/edit

**Comment by frescoal** [comment]
Please try with the latest APK 11h32 I just did and it worked fine
