### ISSUE TITLE
Low Risk for HIV DF recommends wrong management

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#238]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
Low risk of HIV recommends "Refer mother for HIV counselling and testing"
-> But HIV of mother = Negative -> Error this management shouldn't appear

**Note : This story can be related to #239** 

## To Reproduce
Follow scenario below

## Expected behavior
“8981 – Refer mother for HIV counselling and testing” should only appear for:
Refuse/Don’t know results to “HIV status of biologic mother” + yes to “Accompanied by mother”

### Registration
Sex -> Male
DoB -> 24 December 2020 -> (~7 Months)

### Complaint Categories
Gastrointestinal (abdominal problems, vomiting) -> Yes
Everyting else -> No

### Basic Measurements
Weight -> 7 kg
Height -> 65 cm
MUAC -> 140 mm
Temp -> 37°

### Medial History
Diarrhea -> Yes
Duration of Diarrhea -> 10
HIV mother - negative -> Negative
Everything else -> No, Empty

### Physical Exams
Everything -> Absent, Normal, No

### Assessments
Nothing

### Final diagnoses
Low risk of HIV -> Agree
Acute diarrhea, Screening and Prevention -> Disagree

### Healthcare questions
Nothing

### Medicines
Nothing

### Formulations
Nothing

### Summary
**Low risk of HIV**
See error -> "Refer mother for HIV counselling and testing" shouldn't appear

## Smartphone
- Lenovo
- Android version 10

**Comment by jouz56k** [comment]
@frescoal 
Updated story -> Probably related to #239

**Comment by frescoal** [comment]
Might be fixed with Management condition test again please
