### ISSUE TITLE
Feeding counselling shown for ALL ages despite having age conditioning in Acute Diarrhea DF

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#239]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
All Feeding counselling managements are shown for Acute diarrhea

## To Reproduce
Replicate acute diarrhea DF as outlined
Go to summary in Final diagnoses stage to see error

## Expected behavior
Instead of displaying all managements for counselling -> Just display (6m-9m)

### Registration
Sex -> Male
DoB -> 24 December 2020 -> (~7 Months)

### Complaint Categories
Gastrointestinal (abdominal problems, vomiting) -> Yes
Everyting else -> No

### Basic Measurements
Weight -> 7 kg
Height -> 65 cm
MUAC -> 140 mm
Temp -> 37°

### Medial History
Diarrhea -> Yes
Duration of Diarrhea -> 10
HIV mother - negative -> Negative
Everything else -> No, Empty

### Physical Exams
Everything -> Absent, Normal, No

### Assessments
Nothing

### Final diagnoses
Acute diarrhea, Low risk of HIV, Screening and Prevention -> Agree

### Healthcare questions
Everything -> Yes

### Medicines
**Acute Diarrhea**
Zinc sulfate 20 mg -> Agree

### Formulations
Zinc sulfate 20 mg -> 20mg dispersible tablet: 1 tablet(s)

### Summary
**Acute Diarrhea**
See error -> All managements are present (condition on age has not been taken into account)

## Smartphone
- Lenovo
- Android version 10

**Comment by frescoal** [comment]
En discussion avec Alan

**Comment by jouz56k** [comment]
@frescoal 
Story updated
