### ISSUE TITLE
IT or logical issue for "Fever"?

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#240]
## Environment
Server : https://liwi-test.wavelab.top
HF : 124 RW Bweyeye standalone
Algorithm : ePOCT+_DYN_RW_Intervention_V0.1

## Describe the bug
Duration of fever asked inappropriately (i.e. CC Fever No and fever within the last 2 days No) when convulsion in present illness = YES

## To Reproduce
1. Open the app
2. Unlock it
3. Open a consultation
4. See details further below

## Expected behavior
Fever asked only if CC Fever=YES OR Basic measurement T° >= 38° OR Fever within the last 2 days = YES

### Registration
Male
DOB 06-04-2019

### Complaint Categories
All no

### Basic Measurements
15 kg
88 cm
16 cm
T° 37°

### Medial History
See duration of fever is asked

## Smartphone (please complete the following information):
 - Device: Lenovo TB-8504F
 - OS: Android 8.1.0

**Comment by jouz56k** [comment]
je me permets de publier celle la même si j'ai pas trop réussi à localiser le problème si c'est IT, ou logic diagram medal-c,
Peut être que vous avez la réponse

**Comment by frescoal** [comment]
Cannot reproduce duration of fever is not shown

**Comment by jouz56k** [comment]
Unable to reproduce also, I close this until reproducted again by medical team
