### ISSUE TITLE
Easy : Unnecessary/confusing text on Final Diagnosis screen

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#241]
## Describe the request
Assume general to all algorithms: On final diagnosis screen have header text "Diagnoses proposed by (name of algorithm)." It seems unnecessary/confusing to give algorithm name (in this case)  EPOCT+_TIMCI_SN_V0.0.  Suggest just have "Proposed diagnoses"

## To Reproduce
1. Go to Diagnoses stage -> Final diagnoses step

## Screenshots
![Screenshot_2021-07-26-08-49-28-695](https://user-images.githubusercontent.com/55558015/126945407-d3b0d15c-ee5b-4593-9742-9886f204dbd9.jpeg)

**Comment by frescoal** [comment]
This was asked by Alan Validate with him

**Comment by jouz56k** [comment]
We keep this one for feature considerations
-> I close it
