### ISSUE TITLE
Medication form not managed issue (50mg rectal artesunate)

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#254]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
Medication form not managed for the drug "50mg rectal artesunate (Weight <10kg)" even if infos are present in medal-c.

## To Reproduce
Replicate acute diarrhea DF as outlined
Go to summary in Final diagnoses stage to see error

## Expected behavior
Should display : "Number of suppositories per administration: 1"

### Registration
Sex -> Male
DoB -> 24 December 2020 -> (~7 Months)

### Complaint Categories
Gastrointestinal (abdominal problems, vomiting) -> Yes
Everyting else -> No

### Basic Measurements
Weight -> 7 kg
Height -> 65 cm
MUAC -> 140 mm
Temp -> 37°

### Medial History
Diarrhea -> Yes
Duration of Diarrhea -> 10
HIV mother - negative -> Negative
Everything else -> No, Empty

### Physical Exams
Everything -> Absent, Normal, No

### Assessments
Nothing

### Final diagnoses
Acute diarrhea -> Agree
Low risk of HIV, Screening and Prevention -> Disagree

### Healthcare questions
Nothing

### Medicines
Select additional drug -> 50mg rectal artesunate (Weight <10kg)
Disagree with Zinc

### Formulations
You can already see error -> Choose the only formulation -> Medication form not managed

### Summary
See error

## Smartphone
- Lenovo
- Android version 10
- APK 1.0.3

**Comment by cini9** [comment]
@jouz56k Where does this text come from : "Number of suppositories per administration: 1" ? I can't find it in the algorithm. Does the sentence need to be built ?

**Comment by jouz56k** [comment]
@cini9 sorry for no quick answer I was on meeting,
I see the story fixed now nice,
If you still need infos tell me
