### ISSUE TITLE
Conditions on drugs have to be implemented

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#256]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
Conditions on drugs in medAL-r are not taken into account from medAL-c

## To Reproduce
Follow the scenario below to observe the issue

## Expected behavior
Conditions on drugs have to be implemented
**Note** : It can be related to the new system of cut-offs using arrows (medAL-c) -> See screenshot (1)

## Screenshots
(1)
![sdfsdfsdfsdfsdf](https://user-images.githubusercontent.com/55558015/127158930-0837c755-414e-4997-aba4-f30810a8e3f2.PNG)
(2)
![Screenshot_2021-07-27-15-25-43-121](https://user-images.githubusercontent.com/55558015/127161613-97c88b24-66fb-467d-8682-dfa20aca3f2a.jpeg)

## Medical Case Info
Link to diagram: https://liwi-test.wavelab.top/algorithms/7/versions/41/diagnoses/3319/final_diagnoses/10030/diagram

### Registration
Birth date : 17 July 2019 (= 741 days ~ 24.36 Months)

### Complaint Categories
Urine + Genital Problems -> Yes
Everything else -> No

### Basic Measurements
Weight -> 11 kg
Height -> 86 cm
MUAC -> 150 mm
Temp -> 37°

### Medial History
Pain with urinating -> YES
HIV -> don’t know
Everything else -> No

### Physical Exams
Everything : Absent, Empty, Not feasible

### Assessments
Nothing

### Final diagnoses
Possible UTI, Low risk of HIV, Screening & Prevention -> Agree

### Healthcare questions
Co-trimoxazole available -> No
Cipro available -> No
Amox-Clav available -> No
Accompanied by mother -> Yes
Vit a in last 6mth -> No
Deworming in last 6mth -> No
Albendazole available -> No
Mebedazole available -> No
Vaccine UTD -> No

### Medecines
See error for Screening and Prevention
See screenshot (2)

## Smartphone
- Lenovo
- Android version 10

**Comment by alanvonlanthen** [comment]
Still not working (TEST, TIMCI TZ, HF79, 2yo kid, diag screening/prevention)
![image](https://user-images.githubusercontent.com/2785940/127202512-d8941977-d0fb-4dbc-bb92-2441cf5849fb.png)
![image](https://user-images.githubusercontent.com/2785940/127202587-8a65013b-3b04-43e0-b680-ec530fdbde83.png)
