### ISSUE TITLE
Issue adding additional drugs with one formulation

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#261]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
When adding an additional drug with one formulation, formulation is preselected.
Even if there is a formulation already preselected, when pressing Next a warning message appears telling us to select a formulation (see screenshot).

## Screenshot
![Screenshot_2021-07-28-11-24-58-700](https://user-images.githubusercontent.com/55558015/127300255-5d58c1d0-2209-48ab-b995-902a743048f8.jpeg)

## To Reproduce
Follow steps outlined to get to Acute Diarrhea Dx
Go to Formulations step
Add an additional drug with one formulation, e.g. 50mg rectal artesunate

## Expected behavior
Drop warning messages for preselected formulation for additional drugs added,

### Registration
Sex -> Male
DoB -> 24 December 2020 -> (~7 Months)

### Complaint Categories
Gastrointestinal (abdominal problems, vomiting) -> Yes
Everyting else -> No

### Basic Measurements
Weight -> 7 kg
Height -> 65 cm
MUAC -> 140 mm
Temp -> 37°

### Medial History
Diarrhea -> Yes
Duration of Diarrhea -> 10
HIV mother - negative -> Negative
Everything else -> No, Empty

### Physical Exams
Everything -> Absent, Normal, No

### Assessments
Nothing

### Final diagnoses
Acute diarrhea, Low risk of HIV, Screening and Prevention -> Agree

## Smartphone
- Lenovo
- Android version 10

**Comment by cini9** [comment]
@jouz56k Couldn't reproduce this one. For me, all drugs with 1 formulation are preselected and do not raise validation errors. Do you know which drug is causing the issue on your side in particular ?

**Comment by frescoal** [comment]
![image](https://user-images.githubusercontent.com/4497195/127467429-217d6f34-a38a-440a-a16b-ba4c33317d11.png)
Cannon reproduce tried adding the same additionals

**Comment by jouz56k** [comment]
@frescoal
The issue is still there, here is a more specific scenario to observe the issue:
1. Agree with a final diagnosis in Final diagnoses step
2. Add manually **Diazepam rectal vials (2-6m)** in Medecines step
3. Go to Formulations step (in Formulations step do nothing -> just come back to Medecines step again)
4. Add manually **Diazepam rectal vials (6-12m)** in Medecines step
5. Go to Formulations step -> Press Next -> See error
