### ISSUE TITLE
Warning message not showing up for WFH z-score

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#264]
## Environment
Server :  https://liwi-test.wavelab.top/
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0

## Describe the bug
When inputting a Weight and a Height corresponding to a WFH z-score of less than -3 the warning message does not show up for the basic measurements step in medal-reader.

Note 1
- See Weight for height in medAL-c, the error message is set for z-scores less than -3, and higher than +3
- URL : https://liwi-test.wavelab.top/algorithms/1/questions/2101/edit

Note 2
- If Height is set to "Not feasible" -> No error message for WFH-score (and if quick fix hide the corresponding z-score display box)

## To Reproduce
1. Go to 'Basic measurements'

## Expected behavior
Warning messages have to appear for WFH z-score

### Registration
Sex : Female
Estimated DoB : 2 Years

### Complaint Categories
All No

### Basic Measurements
Weight : 6kg, Height : 70 cm => "true" z-score less than -3
-> See OMS table : https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/weight-for-length-height/girls-simplified-field-tables---weight-for-height-2-to-5-years-(z-scores).pdf?sfvrsn=4c1d474e_2
-> See error : No warning for WFH z-score

## Smartphone
 - Lenovo
 - Android version 10

**Comment by frescoal** [comment]
The warning is triggerd when the value is lower than -3 or bigger than 3, But the reference table doesn't handle values lower than 3 or bigger than 3 so the message will never been shown
