### ISSUE TITLE
Warning message not showing up for MUAC-for-age z-score

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#265]
## Environment
Server :  https://liwi-test.wavelab.top/
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0

## Describe the bug
When inputting a MUAC corresponding to a MUAC-for-age z-score of less than -3 the warning message does not show up for the basic measurements step in medal-reader.

Note 1
- See MUAC for age z-score in medAL-c, the error message is set for z-scores less than -3, and higher than +3
- URL : https://liwi-test.wavelab.top/algorithms/1/questions/99/edit

Note 2
- If MUAC is set to "Not feasible" -> No error message for MUAC-for-age z-score (and if quick fix hide the corresponding z-score display box)

## To Reproduce
1. Go to 'Basic measurements'

## Expected behavior
Warning messages have to appear for MUAC-for-age z-score

### Registration
Sex : Female
Estimated DoB : 2 Years

### Complaint Categories
All No

### Basic Measurements
MUAC : 12 => "true" z-score less than -3
-> See OMS table : https://cdn.who.int/media/docs/default-source/child-growth/child-growth-standards/indicators/arm-circumference-for-age/girls-simplified-field-tables-arm-circumference-for-age-3-months-to-5-years-(percentiles).pdf?sfvrsn=f09befa0_2
-> See error : No warning for MUAC-for-age z-score

## Smartphone
 - Lenovo
 - Android version 10

**Comment by cini9** [comment]
Same as for #264 the muac-for-age-z-score warning is defined after +-3 and the reference table only goes from -3 to +3
