### ISSUE TITLE
Referral question not appearing (medAL-r and c issue)

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#266]
## Environment
Server :  https://liwi-test.wavelab.top/
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0

## Describe the bug
The question (variable) "R11 - Did you prescribe an antibiotic..." does not appear on the final step: "Referral" in medal-reader.
It also does not appear in medal-creator on the "Full consultation order" tab, despite appearing in the "Registration and triage variables".

Links
- R11 : https://liwi-test.wavelab.top/algorithms/1/questions/10125/edit
- Registration and triage variables : https://liwi-test.wavelab.top/algorithms/1/versions/1
- Full consultation order : https://liwi-test.wavelab.top/algorithms/1/versions/1

## Smartphone
 - Lenovo
 - Android version 10

**Comment by alanvonlanthen** [comment]
Complement to lin 2: R11 correctly declared in Reg&triage variables: 
![image](https://user-images.githubusercontent.com/2785940/127344795-5e11bba2-f0c9-48c2-9c2c-4602a0e745a8.png)

Complement to link 3: R11 does not appear in Full consultation order:
![image](https://user-images.githubusercontent.com/2785940/127344564-84dfc352-ba56-4945-a40e-8c3839a200ce.png)

**Comment by ManuBarchich** [comment]
Problème de données, Fixed.
