### ISSUE TITLE
Unable to reach severe dehydration

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#268]
## Environment
Server :  https://liwi-test.wavelab.top/]
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0
APK: 20210728

## Describe the bug
Unable to reach diagnosis of severe dehydration
Moreover: A87 - Oral fluid test should appear

## To Reproduce
1. Go to 'Assessments' -> Oral fuild test doesn't appear

## Expected behavior
Oral fuild test sould appear to reach severe dehydration

## Medical Case Info (if applicable)
Link to diagram: https://liwi-test.wavelab.top/algorithms/1/versions/1/diagnoses/91/diagram#

### Registration
Gender : Female
Estimated BoD : 3 years

### Complaint Categories
Gastro -> Yes
Everything else -> No

### Basic Measurements
Weight -> 12kg
Temp -> 37°

### Medial History
Loose/liquid stools -> Yes
Number of loose/liquids -> 4
Duration of diarrhea -> 2
Everything else -> No, Negative, Not feasible

### Physical Exams
Sunken eyes -> Present
Everything else -> Absent normal

### Assessments
See error

##Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by cini9** [comment]
@ManuBarchich Le bug vient de l'algo. Fait moi signe et we check together
