### ISSUE TITLE
"i" button issue 

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#272]
## Environment
Server : https://liwi-test.wavelab.top/
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0

## Describe the bug
"i" button not showing up for variables that don't have a description, but have a picture

## To Reproduce
Go to final diagnosis Mild/Moderate anemia following the scenario below

## Expected behavior
Show "i" button to all variables that have a description OR picture associated to the variable

## Screenshots
![Screenshot_2021-07-29-12-06-06-213](https://user-images.githubusercontent.com/55558015/127473521-21496ec6-17ff-450b-832a-d7901eeb714c.jpeg)

## Medical Case Info
Link to diagram: https://liwi-test.wavelab.top/algorithms/1/versions/1/diagnoses/933/diagram
Link to picture: https://liwi-test.wavelab.top/algorithms/1/versions/1/diagnoses/933/final_diagnoses/1664/edit?source=version

### Registration
Estimated BoD: 3 Months

### Complaint Categories
All No

### Basic Measurements
Weight -> 8kg
Height -> Not feasible
MUAC -> Not feasible
Temp -> 38°

### Medial History
Duration of fever -> 2
Everything else -> No, Negative

### Physical Exams
Everything -> Absent, No

### Assessments
Hemoglobine -> 7
Everything else -> Not feasible

### Final diagnoses
See error -> Not "i" button for Mild/Moderate anemia

##Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by alanvonlanthen** [comment]
Sorry, I realize this wasn't explicitely mentioned in the original issue. Nevertheless, the same behaviour is needed in the list of additional diagnoses too. 
(Actually, if feasible, the behaviour needs to be consistent wherever an [i] is displayed)
![image](https://user-images.githubusercontent.com/2785940/127547965-d0ed6a5d-aa07-4f98-b30f-fdce07a87855.png)

**Comment by cini9** [comment]
Done
