### ISSUE TITLE
Able to reach both fever without source: bacterial and viral

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#278]
## Environment
Server :  https://liwi-test.wavelab.top/
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+Timci_SN_V0.0

## Describe the bug
Following path of medAL-creator diagram of Fever without source, we reach bacterial and viral fever without source
-> The issue is that only one should be display
-> Following the scenario below only viral should appear

## To Reproduce
Folow the scenario below 

## Expected behavior
Only one should be display (viral for the scenario below)

## Screenshots
![Screenshot_2021-07-29-15-51-39-938](https://user-images.githubusercontent.com/55558015/127504718-692a099e-82fa-4b3c-a76b-92111de38e1f.jpeg)

## Medical Case Info
Link to diagram: https://liwi-test.wavelab.top/algorithms/7/versions/41/diagnoses/3240/diagram#

### Registration
Estimated BoD -> 92

### Complaint Categories
All No

### Basic Measurements
Weight -> 8kg
Temp -> Child doesn't feel hot
Everything else -> Not feasible

### Medial History
Fever within the last 2 days -> Yes
Duration of fever -> 2 days
Everything else -> No, Negative

### Physical Exams
Jaundice -> Yes
Everything else -> Absent

### Assessments
Malaria rapid test -> Negative
Well appearing -> Yes

### Final diagnoses
Fever without source: presumed bacterial infection -> Shouldn't appear

## Smartphone
 - Device: Lenovo
 - Android version 10

**Comment by frescoal** [comment]
Si Jaundice est a Présent Well Appearing n'apparait pas

**Comment by jouz56k** [comment]
@frescoal
Je vois l'issue fixed, est-elle fixed en ayant supposé le scenario avec Jaundice -> Absent?
Car c'est Absent que je voulais noter pour Jaundice, j'ai fait une faute de frappe en rédigeant la story.

**Comment by jouz56k** [comment]
Je close Alan m'a expliquer que c'est ok maintenant
