### ISSUE TITLE
Cannot reach uncomplicated infectious lymphadenitis

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#285]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
Cannot reach uncomplicated infectious lymphadenitis

## To Reproduce
Folow the scenario below.

## Expected behavior
Observing NECK MASS diagram in medAL-c, **uncomplicated infectious lymphadenitis** should appear following the scenario below.

## Medical Case Info
Link to diagram: https://liwi-test.wavelab.top/algorithms/7/versions/41/diagnoses/3267/diagram

### Registration
Birth date : 17 May 2018 (~38.47 Months)

### Complaint Categories
Ear, Nose, Throat

### Basic Measurements
Weight: 14kg
Height: 94cm
MUAC: 155mm
Temp: 37 °C

### Medial History
Neck lump / lymphadenopathy : Yes
HIV mother : Negative
Everything else : No

### Physical Exams
Local tenderness of neck mass : Yes
Size of neck mass : 2
Everything else : No, Absent

### Assessments
N/A

### Final diagnoses
See error : There is no uncomplicated infectious lymphadenitis

## Smartphone
 - Device: Lenovo
 - Android version 10

**Comment by cini9** [comment]
@jouz56k I don't think that this is a bug. In the algorithm that is used, DF73 - uncomplicated infectious lymphadenitis is excluded by DF70 - Viral acute pharyngitis

![Screenshot 2021-07-30 at 12 24 41](https://user-images.githubusercontent.com/56114997/127639767-4e683f23-5daf-42bf-89ae-7eaeb4bbec8b.png)

If you click on Disagree for Pharyngitis, uncomplicated infectious lymphadentis shows up :
![Screenshot 2021-07-30 at 12 26 53](https://user-images.githubusercontent.com/56114997/127639996-23d0a09e-d011-4054-80ee-10f431af035d.png)

@frescoal Correct me if im wrong ?

**Comment by jouz56k** [comment]
Bien vu @cini9
