### ISSUE TITLE
Issue with exclusuions : Azithro excluding Amox HD in Medicines step

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#286]
## Environment
Server : https://liwi-test.wavelab.top
HF : SN Testing Health Facility TIMCI (Standalone)
Algorithm : ePOCT+_TIMCI_SN_V0.0

## Describe the bug
**Azithro** (DR42) excludes **Amox** (DR33),
but arriving in Medecines step we see (Azith for Dysentry) and (Amox HD for Pneumonia).
Note: However we can observe exclusion when agree and disagree with drugs. In fact, **Amox** disappears.

## To Reproduce
Follow the scenario below to see error

## Expected behavior
Arriving in Medicines step, **Amox** (DR33) shouldn't appear as it is excluded by **Azithro** (DR42).

## Screenshots
**medAL-c proof of exclusion**
![dfgdagfdagfdg](https://user-images.githubusercontent.com/55558015/127629504-68c86154-a6d6-45a6-ab20-cffdc5c1d877.PNG)

**medAL-r no exclusion**
![Screenshot_2021-07-30-11-18-13-276](https://user-images.githubusercontent.com/55558015/127631609-f9045341-ccef-42fa-ae4c-33be08a1ef88.jpeg)

### Registration
Sex : Male
Birth date : 17 July 2017

### Complaint Categories
Urine or genital problems : Yes
Everything else : No

### Basic Measurements
Weight : 16kg
Height : 103cm
MUAC : 160mm
Temp : 38.4 °C

### Medial History
Fever within the last 2 days : Yes
Duration of fever (days) : 3
Difficulty breathing : Yes
Diarrhea (loos/liquid stool) : Yes
Duration of diarrhea : 10
Blood in stool : Yes
HIV mother : Negative
Everything else : No, Empty

### Physical Exams
Wheezing : Yes
Chest indrawing : Yes
Oxygen saturation (%) : 93
Respiratory rate : 28
Everything else : No, Absent, Normal

### Assessments
Malaria rapid diagnostic test : Negative
Number of illness episodes with wheezing : 1
Wheeze: Attempt trial of bronchodilator : Improvement
Chest indrawing after bronchodilator : No
Respiratory rate after bronchodilator : 40

### Final diagnoses
Pneumonia : Agree
Dysentery : Agree
Everything else : Disagree

### Healthcare questions
Is Amoxicillin available : Yes
Is oral Ciprofloxacin available : No
Is Azithromycin available : Yes

### Medicines
See error (See screenshot : medAL-r no exclusion)

## Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by frescoal** [comment]
Ok vu avec Alan
