### ISSUE TITLE
Too small pictures in "i" button (PH-#2477)

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#290]
## Environment
Server : https://liwi-test.wavelab.top/
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0

## Describe the bug
Pictures in "i" button are too small

## To Reproduce
Go to final diagnosis Mild/Moderate anemia following the scenario below

## Expected behavior
Should be able to zoom in the image view (Screenshot 2) to observe text in the picture

## Screenshots

**Screenshot 1**
**![Screenshot_2021-08-02-10-52-53-279](https://user-images.githubusercontent.com/55558015/127834294-91e7f9fa-3bda-4e0e-831a-5c6b57e3a5d0.jpeg)**

**Screenshot 2**
![Screenshot_2021-08-02-10-53-34-328](https://user-images.githubusercontent.com/55558015/127834326-1bb38140-929a-496d-a173-66f19b9943fb.jpeg)

## Medical Case Info
Link to diagram: https://liwi-test.wavelab.top/algorithms/1/versions/1/diagnoses/933/diagram
Link to picture: https://liwi-test.wavelab.top/algorithms/1/versions/1/diagnoses/933/final_diagnoses/1664/edit?source=version

### Registration
Estimated BoD: 3 Months

### Complaint Categories
All No

### Basic Measurements
Weight -> 8kg
Height -> Not feasible
MUAC -> Not feasible
Temp -> 38°

### Medial History
Duration of fever -> 2
Everything else -> No, Negative

### Physical Exams
Everything -> Absent, No

### Assessments
Hemoglobine -> 7
Everything else -> Not feasible

### Final diagnoses
See error -> Not "i" button for Mild/Moderate anemia

## Smartphone
 - Device: Lenovo
 - Android version 10

**Comment by cini9** [comment]
@jouz56k I don't think this is a bug. It's a feature that needs to be developed into the application.

**Comment by ArnaudPol** [comment]
It seems that there is still an issue with this functionality. It is now possible to zoom on the image but the image is cropped. It is not possible to see the entire image. See screenshots below. 
![Screenshot_20210824-092650_medAL-reader 1](https://user-images.githubusercontent.com/88440132/130583639-61eed2d9-5291-4f18-9939-83355281e88f.jpg)
![Screenshot_20210824-092653_medAL-reader 1](https://user-images.githubusercontent.com/88440132/130583659-c9a77364-b2b0-45d2-be11-f9b6b83fad97.jpg)
