### ISSUE TITLE
Offline mode, error message when clicking on Next & button disappears

### ISSUE THREAD

**Issue by ArnaudPol** [Wavemind/liwi-medal-reader#299]
## Environment

Server : https://liwi-test.wavelab.top/
HF : CH test rasPi bureau Renzo
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
APK version : 1.0.77

## Describe the bug
When  creating a new patient and clicking on "Next" while being offline, an error shows and the Next button disappears, being replaced by a red box showing "N". Afterwards, this red box stays and is displayed on all consultations, even if the user is logged in.

## To Reproduce
1. Make sure to be offline.
2. Click on "New patient".
3. Fill in the mandatory fields.
4. Click on "Next".
5. Leave the consultation.
6. Make sure to be online.
7. Enter a new consultation that is not yet completed.

## Expected behavior
After clicking on the Next button, the user should be able to continue filling other informations about the consultation. The Next button should not disappear.

##Smartphone
Samsung, Lenovo

**Comment by quentingirard** [comment]
Probably already fixed. A new test is needed the next APK
