### ISSUE TITLE
Error thrown when trying to enter a consultation when offline.

### ISSUE THREAD

**Issue by ArnaudPol** [Wavemind/liwi-medal-reader#301]
## Environment

Server : https://liwi-test.wavelab.top/
HF : CH test rasPi bureau Renzo
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
APK version : 1.0.77

## Describe the bug
When trying to enter a consultation while being offline, an error is thrown. See screenshot.

## To Reproduce
1. Make sure to be offline.
2. Enter an already existing case under latest consultations on the home screen.

## Expected behavior
The error should be caught, avoiding a crash of the application.

## Screenshots
![Screenshot_20210805-085356_medAL-reader](https://user-images.githubusercontent.com/88440132/128305931-b4c90188-c304-4876-86e0-b94a8a29b917.jpg)

## Smartphone
Device: Android
Version: Android version 10

**Comment by quentingirard** [comment]
Could you be more specific in "To Reproduce" part please

Questions:

- Are you trying to open an existing case or create a new one ?
- From where are you trying to open/create a case ?

**Comment by ArnaudPol** [comment]
> Could you be more specific in "To Reproduce" part please
> 
> Questions:
> 
> * Are you trying to open an existing case or create a new one ?
> * From where are you trying to open/create a case ?

I tried to be more specific. The bug is simple to reproduce.

**Comment by quentingirard** [comment]
Another questions:

- Patient was created when connection was up ?
- On which screen you lost the connection ?

**Comment by ArnaudPol** [comment]
> Another questions:
> 
> * Patient was created when connection was up ?
> * On which screen you lost the connection ?

Yes, patients were created online. Connection was lost on the main screen, after retrieving the list of consultations.

**Comment by alanvonlanthen** [comment]
@quentingirard le problème est toujours là. Et c'est logique que ça pète en fait... Il faut juste trouver un moyen plus élégant de catcher l'erreur ;) 
Pour reproduire (en client-serveur only) : 
* Situation initiale : tablette connectée. Hub visible. Afficher la liste de patients. 
* Couper le réseau (ou passer en mode avion). La liste des patients est toujours affichée sur la tablette
* Cliquer sur un des patients : ça pète

Options possibles pour gérer le souci de manière plus élégante : 
1. (Préférée): catcher l'erreur et afficher "Failsafe mode activated. Server not reachable. This consultation cannot be loaded on the reader" (fr: "Mode dégradé activé. Serveur inaccessible. Cette consultation ne peut pas être chargée dans le reader")
2. (Pas terrible mais mieux que l'écran rouge): si failsafe s'enclenche quand on est sur la liste de patients ou de consultations, rafraîchir la liste)
3. Toute autre proposition bienvenue :)

**Comment by quentingirard** [comment]
J'ai mis en place un refresh de la vue si le status de connexion à changer. A test si niveau UX ça semble correct
