### ISSUE TITLE
QSS not working properly?

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#315]
## Environment
Server : https://medalc.unisante.ch/

Algo : ePOCT+_DYN_TZ_V1.0
HF : #REFACTO TEST INTERVENTION DYNAMIC TZ (76)

Algo : ePOCT+_DYN_RW_Intervention_V0.1
HF : #REFACTO TEST INTERVENTION DYNAMIC RW (78)

## Describe the bug
Algos constructed same way for Dyn TZ and RW, but a question is missing in medAL-reader for Dyn TZ when reaching the QSS Dehydration risk of dehydration diagnosis in medAL-creator
"How many times did the child vomit in the past 24 hours?" is missing in medAL-reader for Dyn TZ.

## To Reproduce 
Follow the scenario below to observe the missing question of Dynamic TZ

## Expected behavior
The missing question should appear

## Screenshots
![dfgbfxcbxvcbxvcb](https://user-images.githubusercontent.com/55558015/128867601-33e80dcb-c6fb-40f2-8148-2ecc58196c96.PNG)
![fsafsafsaf](https://user-images.githubusercontent.com/55558015/128867607-561dcf7f-0a00-4255-b0d7-298f1f254c8d.PNG)

## Medical Case Info
URL of Diagrams
Dyn TZ 
Dehydration : https://medalc.unisante.ch/algorithms/1/versions/1/diagnoses/91/diagram#
Dehydration risk : https://medalc.unisante.ch/questions_sequences/459/diagram
Dyn RW
Dehydration : https://medalc.unisante.ch/algorithms/6/versions/39/diagnoses/3107/diagram
Dehydration risk : https://medalc.unisante.ch/questions_sequences/7447/diagram

### Registration
Birth date : 5 May 2017

### Complaint Categories
Fever, Gastrointestinal : Yes

### Basic Measurements
Weight : 4.4
Height : 64
MUAC : Not feasible
Temp : 39.9

### Medial History
Loose or liquid stools : Yes -> See error, no "How many times did the child vomit in the past 24 hours?" for Dyn TZ

## Smartphone
 - Lenovo, Samsung
 - Android version 10

**Comment by frescoal** [comment]
On my side it works if you say yes to Vomiting everything
https://medalc.unisante.ch/questions_sequences/7252/diagram#
