### ISSUE TITLE
Unable mandatory consent when no is selected

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#317]
## Environment
Server : https://medalc.unisante.ch/
Dyn TZ and Dyn RW

## Request
Unable mandatory consent when no is selected

## Expected behavior
When Consent is setted to no, currently we can't save Registration step.
Unable mandatory consent when it is setted to no

**Comment by frescoal** [comment]
On a repliqué le comportement de l'ancienne application.
Est-ce que l'on veut changer ça ?

**Comment by jouz56k** [comment]
Yes please, unable mandatory consent when no is selected in order to reach 1st Assessments stage without consent.
