### ISSUE TITLE
Crash related to Zinc sulfate 10 mg (half a tablet) (ID:9564)

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#335]
## Environment

Server : prod
Health facility: https://medalc.unisante.ch/health_facilities/149
Architecture : standalone
App version : APK 1.0.84

## Describe the bug
Crash related to Zinc sulfate 10 mg (half a tablet) when adding the drug manually using dropdown list

## To Reproduce
1. Add a final diagnosis
2. From dropdown list search and add Zinc sulfate 10 mg (half a tablet) manually
3. Press Next in Formulation step
4. See error -> Crash

## Expected behavior
Should no crash

## Smartphone (please complete the following information):
 - Device: Lenovo
 - Android version 10

**Comment by quentingirard** [comment]
Cannot reproduce on an existing patient or with a new one.

Could you give me an exemple of case ?
