### ISSUE TITLE
Fixed dose medicines issue (PH-#2525)

### ISSUE THREAD

**Issue by quentingirard** [Wavemind/liwi-medal-reader#338]
## Environment

Server : [dev/staging/prod]
Server : https://medalc.unisante.ch
HF : #REFACTO TEST INTERVENTION DYNAMIC TZ
Algorithm : ePOCT+_DYN_TZ_V1.0
APK : 1.0.84

## Describe the bug
Dispensing description doesn't appear for capsules and tablets fixed dose in medAL-reader.

## To Reproduce
1. Go to Final diagnoses step
2. Add "Severe complicated measles
3. Say yes to Vitamin A in HQ questions
4. Agree with Vitamin A in Medicines step
5. Select 50,000 UI for Vitamin A in Formulations step
6. See error in summary no dispensing description for Vitamin A

Note: In screenshot, we can see same issue for Mebendazole po (deworming) (fixed dose tablet)

## Expected behavior
Dispensing description should appear

## Screenshots
refere to https://wavemind.atlassian.net/secure/RapidBoard.jspa?rapidView=8&projectKey=LIWI&modal=detail&selectedIssue=LIWI-1549&sprint=226

**Comment by frescoal** [comment]
Fixed 87
