### ISSUE TITLE
For investigation. Bug? Missing management for BActerial pneumonia (PH-#2524)

### ISSUE THREAD

**Issue by quentingirard** [Wavemind/liwi-medal-reader#340]
## Environment

Server :  prod
HF : CH Dynamic Intervention Standalone test
Algorithm : ePOCT+_DYN_TZ_V1.0

## Describe the bug
No inpatient referral: reasons to return" management does not show up

## Expected behavior
Management should be displayed for bacterial pneumonia

### Registration
Birth date : 5 December 2020
Gender: Female

### Complaint Categories
- Fever
- Respiratory complaint

### Basic Measurements
- Weight 9.1kg,
- Length 67.2cm
-  MUAC 14.5cm
-  T°C: 38.2°C

### Medial History
Select no/absent to all, except fever 2 days, cough 3 days

### Physical Exams
- RR: 80/min
- SpO2: 93%, HR 100
- Rest neg/absent

### Assessments
- mRDT: neg
- Hb: 11.2
- CRP: >80mg/l

### Diagnoses
- Bacterial pneumonia
- Prevention and screening

### Treatment conditions
- Yes to all

### Medicines
- Accept all

### Medicine Formulation
- Select most appropriate formulation (syrup for paracetamol, tablets for amoxicillin)

### Treatment and Management
- amoxi + pcm
- Mgt: ensure adequate fluid and calorie intake, counselling to preven the spread or respiratory illness

**Comment by frescoal** [comment]
Fixed in 87
