### ISSUE TITLE
For investigation. Bug? Unable to reach malaria diagnosis TIMCI KE (PH-#2535)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#342]
## Environment
Server :Prod
HF : Kenya Test facility
Algorithm : ePOCT+_TIMCI_KE_V0.0
APK : 1.0.86

## Bug
Question 'high risk malaria area (or recent travel to)' not appearing for a child with fever; consequently no malaria test is proposed.

## To Reproduce
3 year old (estimated age) male, inital visit, no recent visit to health facility
No emergency
Weight 14kg Height 103cm MUAC 14cm Temp 36.9 Oxygen saturation 96 HR 102
CC fever
AVPU = Alert; No danger signs
Fever = yes - 3 days
All else in medical history = normal / negative
PE: Some pallor (not severe); all else normal / no

## Expected behavior
Should prompt question 'high risk malaria area' as a complementary medical history question in the physical exam, and then = yes --> malaria test or no --> obvious source of fever --> no --> malaria test (see https://medalc.unisante.ch/questions_sequences/11941/diagram)

## Smartphone
 - Device: lenovo tablet and google pixel phone

Initially, PS 'reason to do malaria test' was set with very high day age range (previous bug incorrectly converted months to huge no. of days (something in region of e.g. 5,425 - 18,350). Have fixed this, but still not working

**Comment by frescoal** [comment]
Well Après une belle et longue analyse des diagrammes et des QS voici ce qu'il en ressort.

Au début j'ai cru que la raison était car Severe Pallor était pas coché mais enfaite non.

La raison est la suivante => Une personne mal intentionnée a mis le CC Général de **"Young Infant"** dans les conditions de la question.

![image](https://user-images.githubusercontent.com/4497195/130465741-8886fcef-73c0-44c8-b342-385c3d02672b.png)

**Comment by alanvonlanthen** [comment]
Pfff.... Désolé pour le temps perdu :( 
Merci pour l'enquête et la conclusion :) 
C'était quelle question, du coup, qui était conditionnée par le CC général YI? Severe Pallor? 
Tu as viré le CC?
