### ISSUE TITLE
Force close medical case after 36 houres (PH#2540)

### ISSUE THREAD

**Issue by quentingirard** [Wavemind/liwi-medal-reader#347]
## Describe the bug
Force close medical case after 36 hours based on last updated

**Comment by alanvonlanthen** [comment]
Reopening the issue. Bug still present :( 

Screenshot from Sept 6, 2021 on app 1.0.90 (updated on Sept 1, 2021)
![Screenshot_20210906-173005_medAL-reader](https://user-images.githubusercontent.com/2785940/132237263-c5f541d6-4631-47e4-8d29-0f2be93e700f.jpg)

![IMG_20210906_175349](https://user-images.githubusercontent.com/2785940/132237282-473a75f7-8696-438e-906b-adc0c4c671ec.jpg)

**Comment by quentingirard** [comment]
Tablette in client-server mode. Issue on medal-hub
