### ISSUE TITLE
Impossible to move to next stage in client-server with instable internet (PH-#2630)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#370]
Set-up:
- Client-server
- DYNAMIC TZ - Intervention arm
- Many different dispensaries (Iziwa, Ketaketa, Ituha, etc)
- APK 1.0.97
 
Bug:
- Not able to continue to next stage (see screen shots) despite all fields filled.

Context that may help explain the issue:
- Internet inconsistent (although some HFs confirm that internet is ok)
- Connected to client server hub

![image](https://user-images.githubusercontent.com/2785940/134896320-0f29db51-44de-458d-b050-8b2105ae0707.png)
![image](https://user-images.githubusercontent.com/2785940/134896340-1d484ee5-fb2f-446c-ac0e-e1da6326d724.png)
![image](https://user-images.githubusercontent.com/2785940/134896360-1cd0df3b-70b4-4460-ba9f-3a6f997d2cd5.png)

**Comment by quentingirard** [comment]
Besoin de plus d'info:

- Réouverture d'un cas ou création de nouveau cas ?
- Nouveau cas sur un patient existant ?
- Le problème arrive uniquement sur le stage "Registration" ?
- Le problème arrive à chaque création de cas ?
- Le problème arrive lors d'un scan de QR code ?
