### ISSUE TITLE
Cases closed in failsafe mode are never pushed back to medAL-hub (PH-#2720)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#393]
## Environment

Server : PROD
Version ID or URL : 1
Health facility ID or URL : Mbuga
Architecture : client-server
App version : 1.0.102+

Cases closed in fail-safe mode don't resync with medAL-hub when the power comes back after 3 days. Renzo ready to receive them. We "just" need to push them #68 

![image](https://user-images.githubusercontent.com/2785940/138487293-8da49c29-b2e6-4b80-b963-a0215aa7f22a.png)
![image](https://user-images.githubusercontent.com/2785940/138487329-1673ba18-cfb8-4e50-94e7-8eea5fe34333.png)

**Comment by quentingirard** [comment]
l'updated_at est rempli sur le reader
