### ISSUE TITLE
Scanning a QR code for an existing patient creates a new patient (PH-#2739)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#400]
Currently, scanning a QR code for an existing patient creates a new consultations (and generates duplicate patients in the DB for some reason). 

Expected behaviour:
* If patient not found => create consultation (as now)
* If patient found => open patient view (the one where the clinician can either see the current consultation if any, the last consultations, the personal info, and where they can create a new consultation if needed)
![image](https://user-images.githubusercontent.com/2785940/140519175-ecad1d17-7b6c-4993-a9ec-92d007da816c.png)

**Comment by quentingirard** [comment]
#404
