### ISSUE TITLE
Formulation drop-down list: additional display instructions per type of formulation (PH-#2751)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#402]
In the Formulation step of medAL-reader, make the following changes to the Formulations Drop-down list

**1. CAPSULE (weight-based)**: display the description (in dotted red box) before the amount (in this example => "50 mg capsule: 3 capsule(s)")
![image](https://user-images.githubusercontent.com/2785940/140542522-5d486882-8d75-4f67-9126-cd0ad3d552c1.png)
     NB: no changes for fixed-dose capsules; what we have currently is exactly what we need
     NB: no changes either for dispersible tablets (weight-based and fixed dose)

2. TABLET (weight-based): display the description (in dotted red box) before the amount (in this example => "Tablet 480mg (Trimpethoprim 80mg, Sulfamethoxazole 400 mg): 1 tablet")
![image](https://user-images.githubusercontent.com/2785940/140542596-90e145c6-20cf-4d39-985b-be978f5254ef.png)
     NB: no changes for fixed-dose tablets; what we have currently is exactly what we need

3. SYRUP/SUSPENSION (weight-based): display the description (in dotted red box) before the amount instead of computing what appears before the amount (in this example => "125mg/5mL syrup: 8.4ml per administration")
![image](https://user-images.githubusercontent.com/2785940/140542660-a9e6ae77-614e-404b-89b1-05bbb1413291.png)
     NB: no changes for fixed-dose syrup/suspension; what we have currently is exactly what we need

4. SOLUTION / OINTMENT (weight-based & fixed dose): display the calculated amount after the description (separated by a colon (:) ). The computation uses the exact same fields as the  
![image](https://user-images.githubusercontent.com/2785940/140542724-cb0f45f1-719f-49cf-a265-224343d0d975.png)

/!\ For solutions and ointments please fix for both weight-based and fixed-doses

5. INHALER (FIXED DOSE). Append amount after the description. In this case: "5mg/ml: 0.5mL per administration"
![image](https://user-images.githubusercontent.com/2785940/140542797-175956ea-dd90-4283-8e2a-be3b3f2e46a5.png)
NB: no change in weight-based inhalers, they work just fine :) 

6. DROPS, CREAM. Append number of applications per administration after the description. In this case: "0.3% (as sulphate) Eye Drops: 1.0 application(s) per administration"
![image](https://user-images.githubusercontent.com/2785940/140542859-b3581652-4bcf-4f91-9030-9aa12260b84a.png)

**Comment by quentingirard** [comment]
- Aucun calcule implémenté dans medAL-R pour les SOLUTION / OINTMENT

**Comment by quentingirard** [comment]
#403

**Comment by alanvonlanthen** [comment]
Coucou @quentingirard 

_⚠️ Certaines descriptions de formulations sont très grandes et donc pas totalement visible lorsqu'on sélectionne une formulation ex: Co-trimoxazole po⚠️_
=> Lisa déjà sensibilisée à la problématique. Elle attend de voir à quoi ça ressemble avant de modifier les descriptions accordingly

_Problème:
SOLUTION / OINTMENT -> Aucun calcule implémenté dans medAL-R_
=> Il faut bien commencer un jour... C'est un gros effort ?


_Questions:
* Pas de changement pour LOTION, GEL, POWDER OF INJECTION qui fonctionne comme CREAM et DROPS ?
* Pas de changement pour PESSARY, SPRAY, PATCH qui fonctionne comme INHALER ?_
=> Exact

**Comment by alanvonlanthen** [comment]
Demandé à Lisa sur quoi est basé la "calculation" pour les ointments et les solutions via Proofhub https://dynamic-project.proofhub.com/bapplite/#app/todos/project-4532906095/list-134322977173/task-210236541423

**Comment by alanvonlanthen** [comment]
The calculated amount needs to be shown as **both the MG** and the **amount (ml, # tablets, # capsules, etc)**.

DOSE (mg):To get the MG first, this is done by using the average of the Minimal-Maximal dose (mg/kg/day) prod boxes multiplied by the patient's Weight (kg), and divided by the Number of Administrations per day PROD boxes.

E.g. MG of Ampicillin for a 5kg (weight) child would be 400mg/kg/day **(min-max dose)** multipled by 5kg **(weight)** = 2000mg divided by 4 **(administrations per day)** = 500mg dose.

AMOUNT NEEDED TO ACHIEVE DOSE: Now that you know the dose needed, the amount will differ per formulation to give as they are all different strengths.

The calculation required per formulation is therefore:

**Concentration (mg in dose)** divided by the **pre-calculated Dose (mg)**, or

If the formulation is a liquid (solution/powder for injection/suspension), you need to cross multiple: **Total drug formulation volume (ml)** multiplied by the **pre-calculated dose**, divided by the **Concentration (mg in dose)**.

Eg. We know we need a 500mg for that child above.

So if using the IM - 250mg/1.5ml formulation: 1.5ml **[total drug formulation (ml)]** multiplied by 500mg **[the pre-calculated dose]** and divide by the 250mg **[concentration (mg in dose)]** = 3ml.

So it would take 3ml of the 250mg/1.5ml formulation is needed to achieve a 500mg dose.

If we used the IV- 500mg/5ml formulation, it would take 5ml to achieve the 500mg dose: 5ml **[total drug formulation (ml)]** multiplied by 500mg **[the pre-calculated dose]** and divide by the 500mg **[concentration (mg in dose)]** = 5ml.
