### ISSUE TITLE
Task: add app version in the JSON file generated by medAL-reader

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#405]
(Will be used for debugging purposes once the JSON file reaches medAL-data)

**Comment by quentingirard** [comment]
Besoin de faire l'ajout de l'information dans le hub aussi

**Comment by alanvonlanthen** [comment]
https://unisante-projets/?controller=TaskViewController&action=show&task_id=14280&project_id=74

**Comment by quentingirard** [comment]
#406
