### ISSUE TITLE
Missing translation for age limit message (PH-#2914)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#430]
also, can't find the key in the translation files :/ 

=> EN "Age out of supported range for this algorithm"
=> FR "Âge hors des seuils gérés par cet algorithme"

![image](https://user-images.githubusercontent.com/2785940/152127453-39e9e5eb-5d33-4137-9cdd-d0d7d4b74322.png)

**Comment by quentingirard** [comment]
Ce n'est pas géré sur medAL-R, c'est une config au niveau de la version. Check avec Manu
