### ISSUE TITLE
top priority: tablets require new medAL-data login without even checking on medAL-data if token has expired (PH-#3199)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#431]
Passport only (versions 114+)

Tablets require new medAL-data login (mostly after AOK update from the store) without checking token with medAL-data. 

People are seeing patterns everywhere (post medAL-r update? post medAL-data update? after the tablet has not been used for a couple of days?), but we haven't figured any clear pattern out yet. Only that it impacts more than half the tablets everywhere and it has become the number 1 issue and top priority.

**Comment by quentingirard** [comment]
Rajouter une notification lorsque le user est redirigé sur la page de login après un refresh token

**Comment by alanvonlanthen** [comment]
looks pretty much fixed with v 119 :)
