### ISSUE TITLE
Unable to login into medal-reader when internet is weak or off (PH-#3205)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#433]
Environment:
DYNAMIC TZ ePOCT v2.1
APK 115+
Client server
 
Problem:
Unable to login when connected to the hub, but there is no internet or very weak internet.
 
Workaround: Put tablet in flight mode, login, and then take tablet off flight mode.

**Comment by quentingirard** [comment]
Unisanté
--------------------------------

- Check avec Renzo si le zip renvoie uniquement une 204
- Ping le data pendant plusieurs jours.
- Mettre en place zip pour emergency content

Wavemind
----------------
- Améliorer le système de récupération de data une fois que le zip est déployé partout

**Comment by alanvonlanthen** [comment]
@quentingirard zip déployé partout. On peut passer à la phase 2 :)
