### ISSUE TITLE
Issues with conditionning WfH/WfL (PH-#3212)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#434]
medAL-r v 118
medAL-c TEST [https://liwi-test.wavelab.top/algorithms/8/versions/44/diagram#](https://liwi-test.wavelab.top/algorithms/8/versions/44/diagram)
medAL-d MASTER/TEST https://195.15.219.241:8080/ (HF1, device 1)
![image](https://user-images.githubusercontent.com/2785940/152814985-6433438c-f0c7-45e8-8318-49668bcc85fc.png)

=> in medAL-reader, 
1. BM11 is not conditionned by BC42 (the question appears whether or not the child was actually measured
2. No z-score appears at all (neither 10894, not 19657)
3. Incidentally, the age is not computed in the header (entered 24 months, estimated)
![image](https://user-images.githubusercontent.com/2785940/152815076-7fc2908c-4bd7-4097-8cd8-798fd6992248.png)

**Comment by quentingirard** [comment]
Bug corrigé dans medAL-R lors de la récupération des questions pour les basic measurements

MedAL-C doit ajouter dans l'ordering les questions avec les tables de références
