### ISSUE TITLE
medAL-reader calls wrong route to retrieve patients list in client-server mode (PH-#2928)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#441]
After analysis by Renzo, this issue has been removed from the "medAL-hub" list in proofhub and moved to the "medAL-reader" list. It only happens in client server mode, though.

Problem: if a patient has _n_ consultations, the patient will appear _n_ times in the patient list view.
![image](https://user-images.githubusercontent.com/2785940/154108515-7f285c95-7630-4594-8c75-0b0ae8fb9a09.png)

Renzo's analysis: 
"There are two different routes to retrieve patient and medical case information from the hub.
 
The first one /api/medical_cases returns each medical case and if a patient has several consultations then this patient appears several times.
 
The second /api/patients returns each patient with a list of medical cases. In this route, the patient appears only once even if he has N consultations.
 
Medal-Reader is therefore free to choose what type of display it wants."

Patient endpoint.jpg:
![image](https://user-images.githubusercontent.com/2785940/154108665-104f6bf3-62af-4cb7-831f-67f4d36411ea.png)

Medical case endpoint.jpg:
![image](https://user-images.githubusercontent.com/2785940/154108719-0ff0c9b0-730b-43b5-abce-4030d61be9cc.png)

@quentingirard please reach out to Renzo if needed (and mention PH-#2928)

**Comment by quentingirard** [comment]
Le screen correspond à la liste des consultations et non à la liste des patients. Vérifiable avec le titre dans le header du screenshot.

Le fait que le même patient s'affiche plusieurs fois dans la liste des consultations est le comportement codé.
