### ISSUE TITLE
app does not automatically switch to French for Senegal (PH-#3254)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#445]
Rule: if FR is the default language in medAL-creator, then medAL-reader must switch to French (algo & UI) after loading the algo on its first run. 

Currently this rule is not applied 

![image](https://user-images.githubusercontent.com/2785940/155117206-aa7a2ccb-8d01-4ffe-ac43-3c29319d6886.png)

**Comment by quentingirard** [comment]
Le data ne me fourni pas la bonne information. Je reçois "en" pour chaque medical staffs lorsque je récupère une HF. Cette valeur doit se baser sur le default language de l'algorithme.

Comme exemple, j'ai pris la version ePOCT+_TIMCI_SN_V0.0 (41) qui a français comme default language sur la prod de medal creator. Mais je reçois "en"

Il nous faudrait un output de l'équipe du data pour savoir comme cette information est géré.

**Comment by quentingirard** [comment]
Décision du 24.02.2022 -> la langue par défaut des cliniciens vont se baser sur la variable d'environnement du medAL-Data
