### ISSUE TITLE
urgent issue: "Default True" conditionning not effective in Treatment diagrams (PH-#3258)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#447]
To reproduce:
TIMCI TZ algo
medAL-data: http://195.15.219.241/
device id: 1747

* 6 month old child. All other answers not relevant
* Additional tests not proposed by algorithm? => 4737 HIV rapid test
* A10 5658 HIV rapid test => 4346 Negative
* Expected Final Diagnosis: DF126 6341 Negative HIV test => ACCEPT
* Expected Management: M171 6052 Negative HIV test (...) /!\ DOES NOT APPEAR DUE TO BC34 (BUG)

cf https://medalcreator.unisante.ch/algorithms/5/versions/34/diagnoses/2622/final_diagnoses/6341/diagram
![image](https://user-images.githubusercontent.com/2785940/155352455-2f369d06-a24d-4271-9038-7607438b455f.png)

**Comment by quentingirard** [comment]
![Screenshot_20220223-172115_medAL-reader](https://user-images.githubusercontent.com/15869493/155361801-ea7c6efb-7333-4e54-8e88-5322f1421a80.jpg)
