### ISSUE TITLE
"Well appearing" not, well, appearing (PH-#3262)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#448]
Timci Kenya APK 1.10.17 -Complicated neck problem dx, treatments not reached as the "Well appearing" question does not appear in the "Tests" section as it should according to the algorithm. 
Tested with 220 day old male child, 8.2Kg 71cm Height 16cm MUAC,
cc Neck problem, Neck lump/swelling = Yes, 4cm size of lump, all other questions answered in negative

to reproduce: 
* medAL-data http://195.15.219.241
* device id 1746

**Comment by quentingirard** [comment]
Un test est uniquement demandé dans le diagramme du diagnostic final. C'est pour ça que le traitement n'apparaît pas.

**Comment by alanvonlanthen** [comment]
al's PH comment after a quick chat with Quentin: 

@Martin Norris @Fenella Beynon  

We have looked into this, and understood what is going on: this scenario is actually not not supposed to work; it's a matter of workflow: 

The PS that promtps the assessment is called by the treatment diagram, which is only interpreted by medAL-reader once the DF has been agreed with. Or this DF agreement business hasn't happened yet when the assessment view is displayed. 

The way around this is to prompt the assessment from within the DD diagram, not the DF diagram. 

I hope this makes sense, happy to have a chat for further details if necessary. 

=> closing the story at wavemind's
