### ISSUE TITLE
Audit trail missing (PH-#3251, PH-#3279)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#458]
In client-server setups, upon exiting the failsafe mode, the reader does not pass the "activities" in the request with the rest of the medical case when it reconnects with the hub

**Comment by Unisante** [comment]
The best would be to add the same key as you already do when posting on medical_cases/{uuid}/activities route.
But in the medical_cases key

```json
"patient": {
    "first_name": "Albert",
    ...,
    "medical_cases": {
        "clinician": "Jean",
        "fail_safe": "",
        ...,
        "activities": {
            "device_id": 1759,
            "step": "registration",
            ...,
        }
    }
}
```

```php
$medical_cases= $request->patient->medical_cases;
$activities= $request->patient->medical_cases->activities;
foreach ($medical_cases as $medical_case) {
    MedicalCase::create();
    foreach ($activities as $activity) {
        Activity::create();
    }
}
```

**Comment by GregMart1n** [comment]
Hello guys, just wanted to check, were are we on this issue and the #463 ?
I'm cleaning up the tickets we have open, like those "cold cases"
Thx

**Comment by quentingirard** [comment]
Yup it's fixed
