### ISSUE TITLE
medAL-reader SQlite issue while trying to create a new patient in client server mode (PH-#3360)

### ISSUE THREAD

**Issue by Devstrap** [Wavemind/liwi-medal-reader#467]
## Environment

Server :  [195.15.219.241](http://195.15.219.241/)
Version ID or URL : [https://medalcreator.unisante.ch/api/v1/versions/39](https://medalcreator.unisante.ch/api/v1/versions/39)
Device ID : 1769
Group ID : 154
medAL-data URL : [195.15.219.241](http://195.15.219.241/)
Architecture : client-server mode
App version : APK 122

## Describe the bug
After a connection lost with the hub, the following error is display at registration step after starting a new case for an existing patient =>Unique constraint failed : medical_cases.id(code 1555 SQLITE_CONSTRAINT_PRIMARYKEY[1555])

## To Reproduce
1. Go to 'patients list'
2. Click on an existing patient
3. Create a new case
4. Fill in all required fields
5. See the error when clicking on Next

Hub as been disconnected during consultation and connection have been restored during opening a new case for the same patient.

## Expected behavior
Next view should be display without error

## Tablet :
 - Device: Samsung SM-T290
 - OS: Android 11

## Additional context
404 on the unlock route for medical case already in local in the Hub log . Not a hub issue.

**Comment by Devstrap** [comment]
Yes for sure 👍 

- deviceId = 1769
- groupId = 154
- medAL-data URL : [195.15.219.241](http://195.15.219.241/)

**Comment by quentingirard** [comment]
I can't reproduce with these info.

Could you provide an example from scratch ?

**Comment by Devstrap** [comment]
I tried to reproduce to bug in the heroku Hub. Unfortunatly I am unable to reproduce the bug for the moment. Come back to you has quickly as possible.

**Comment by alanvonlanthen** [comment]
Dropped

**Comment by alanvonlanthen** [comment]
replicated systematically: 
medAL-data: http://195.15.219.241
device id 1767
group_id 155 (Client server test .4) [using ePOCT+_DYN_TZ_V2.1]
1. create a patient and a consultation => close consultation
2. create a new consultation for this patient (from the patients list)
3. during the registration, loose the connection (flight mode or unplug hub)
4. cry
![image](https://user-images.githubusercontent.com/2785940/186199472-c55a4acd-35b6-4ba0-87e7-6d4dc63ad4c9.png)
