### ISSUE TITLE
medAL-reader crash when token is revok and the application is not completly close (PH-#3363)

### ISSUE THREAD

**Issue by Devstrap** [Wavemind/liwi-medal-reader#470]
## Environment

Server : prod
Version ID: 39 / [https://medalcreator.unisante.ch/algorithms/6/versions/39](https://medalcreator.unisante.ch/algorithms/6/versions/39)
Health facility ID: 154
medAl-Data URL : [195.15.219.241](http://195.15.219.241)
Architecture : client-server
Device ID : 1797
App version : 1.0.122

## Describe the bug
If the token has been revoked or the refresh token is invalid for the device and you minimize the application; medAL-reader crash when you reopen it after enter the PIN code due to inexistant token in medAL-data.

## To Reproduce
1. Open medAL-reader and connect the tablet to medAL-data to an HF with a device and a medical-staff
2. Enter the PIN for the Health Facility in which the tablet is enrolled
3. Once connected revok the token for the tablet in medAL-data
4. Minimze the application
5. Reopen the application and entrer the PIN code
6. See the error display in medAL-reader

## Expected behavior
medAL-reader should display the **connect to medAL-data view** in this scenario.

## Additional context
If you revoke the token and close the application completly the view **connect to medAL-data** is display as expected.

**Comment by Unisante** [comment]
We have added the route /tokeninfo which allows you to check the validity of the access token.

**Comment by alanvonlanthen** [comment]
Still not satisfactory, as the whole content of the tablet has to be wiped before anything can be done before re-enrolling the tablet => https://github.com/Wavemind/liwi-medal-reader/issues/498 

Since there is a new issue for this, the current one may be closed
