### ISSUE TITLE
Missing mandatory id key for some nodes in the ePOCT+_DYN_RW_Control_Arm_v0.1_PROD algorithm 

### ISSUE THREAD

**Issue by Unisante** [Wavemind/liwi-medal-reader#474]
## Environment

Server : prod
Version ID or medAl-Creator URL: [40](https://medalcreator.unisante.ch/api/v1/versions/40)
Architecture : client-server
App version : 1.0.122.10001212

## Describe the bug
Missing mandatory id key for nodes : 
    "7648": { "answer": null, "value": null },
    "7773": { "answer": null, "value": "" },
    "7782": { "answer": null, "value": null },
    "7786": { "answer": null, "value": null },
    "7838": { "answer": null, "value": null },
    "7955": { "answer": null, "value": null },
    "7956": { "answer": null, "value": null },
    "8110": { "answer": null, "value": null },
    "8468": { "answer": null, "value": null },
    "10082": { "answer": null, "value": "" },
    "7837": { "answer": null, "value": null },
    "7955": { "answer": null, "value": null },
    "7956": { "answer": null, "value": null }

**Comment by quentingirard** [comment]
I'm not able to reproduce currently

There is an example of values send for activities in **Tests** stage
![image](https://user-images.githubusercontent.com/15869493/163403007-b72a9157-885f-40f1-bc01-e43d026fa0fa.png)

How do you proceed activities before sending it to the data in hub ?

**Comment by quentingirard** [comment]
Dropped
