### ISSUE TITLE
Re-enrolling previously enrolled medAL-reader (PH-#3634)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#498]
Currently if a reader gets un-enrolled in medAL-data, the following message apprears on the reader, and the user is stuck forever
![image](https://user-images.githubusercontent.com/2785940/170991232-761e37f5-7537-47a9-b11c-6d117119cd98.png)

We need to offer the following 2 options: 

1. If a token cannot be refreshed, instead of displaying the zip file message, display: 
EN: "Security token revoked. Please ask your IT manager to enrol device <device id> in health facility <group_id> on medAL-data <server_id>"
FR: "Jeton de sécurité révoqué. Veuillez demander à votre répondant informatique d'enroller le device  <device id> dans le centre de santé <group_id> sur medAL-data <server_id>"

2. Offer an option to re-enroll the tablet by displaying the initial setup form (server IP / device_id) underneath the PIN pad. Label: 
EN: "Re-enroll with another device_id (do this only if you know exactly what you are doing)
FR: "Ré-enrôler avec un autre device_id (ne faites cela que si vous savez exactement ce que vous faites)

**Comment by quentingirard** [comment]
Handle unassign device from a health facility isn't handled. Need a new spec for estimation.

**Comment by alanvonlanthen** [comment]
Discussion / décision 08 juin 2022: 
* medAL-data catche bien cette erreur mais n'envoie pas l'info à medAL-reader
* côté reader, on a donc un token et un refresh token valides (indépendants de la HF), mais une erreur 500 à cause de l'absence de HF. Insuffisant pour gérer l'exception proprement. 
* Du coup, story [PH-#3634](https://dynamic-project.proofhub.com/bapplite/#app/todos/project-4532906095/list-191328334536/task-248142983618) renvoyée chez Sylvain pour le moment
* Côté medAL-reader, une fois qu'on recevra les statuts corrects de medAL-data, on affichera simplement des messages d'erreur. On peut clôturer cette isue, la story [1745](https://wavemind.atlassian.net/browse/LIWI-1745)  prend le relais
