### ISSUE TITLE
Syncing issues (PH-#3660) (PH-#3683)

### ISSUE THREAD

**Issue by alanvonlanthen** [Wavemind/liwi-medal-reader#501]
(Seems to have happened in Kenya on June 13 at 20h24 with medAL-reader 1.1.2.101219)
Please check we only send 5 cases at a time in each ZIP file

**Comment by quentingirard** [comment]
Tested with 2, 5, 7 and 10 cases without any issues (each time batch of maximum 5 cases) in standalone mode.

**Comment by alanvonlanthen** [comment]
Delivered with 1.1.4

**Comment by alanvonlanthen** [comment]
Fixed with 1.1.4 :)

**Comment by quentingirard** [comment]
Bug persist. Waiting more information.

**Comment by alanvonlanthen** [comment]
@quentingirard reçu hier soir : 

From: Stanslaus Odhiambo <stodhiambo@path.org> 
Sent: lundi, 18 juillet 2022 21:45
To: Faivre Vincent <Vincent.Faivre@unisante.ch>
Cc: Schaufelberger Sylvain <Sylvain.Schaufelberger@unisante.ch>; Vonlanthen Alan <Alan.Vonlanthen@unisante.ch>
Subject: RE: New version of medAL-reader on the store

Hi Vincent,

Making a follow up on this issue that continues to appear. The two tablets have the latest version of medal-R installed (1.1.15) and are running Android 11.
Kindly check the captures below:

Regard
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/2785940/179746516-d815aac5-6ca0-4b41-a560-c85d31085f34.png)
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/2785940/179746539-297db1ce-250f-44ba-bb67-a5e8b1c01959.png)

**Comment by GregMart1n** [comment]
Reaching out to the field to know if this is still an issue.

**Comment by quentingirard** [comment]
Any news @GregMart1n ?
