### ISSUE TITLE
Modify consultation auto-close from 36h to 12h (PH#3696)

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#514]
For medAL-reader, a consultation should be auto-closed after 12h.
I believe it is 36h now.

**Comment by quentingirard** [comment]
@GregMart1n medAl-hub need to be updated too. Sylvain has been informed ?

**Comment by GregMart1n** [comment]
@quentingirard Thanks for the reminder. We are still discussing this point internally. The hub would impact other regions.

**Comment by alanvonlanthen** [comment]
@GregMart1n T'as pu checker avec TIMCI s'ils veulent la modif en standalone?

**Comment by GregMart1n** [comment]
@alanvonlanthen Oui ok pour TIMCI.
@quentingirard comment ce passe les dates de release ? Est-ce qu'on doit en discuter ou c'est plus ou moins prédéfini?
