### ISSUE TITLE
Mandatory steps can be bypassed

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#516]
## Environment

Server : PROD
Version ID or medAl-Creator URL: -
Health facility ID or medAl-Data URL : All
Architecture : client-server yes, standalone not sure
App version : 1.1.5

## Describe the bug
When a new consultation is created for an existing patient, it appears that sometime the screens after "registration" are all white, no fields. It is possible to click on NEXT til the referral step, and close the consultation. Meaning that we have now consultations that are manually closed with mandatory fields not populated.

## To Reproduce
This still need to be figured out, as it seems to be random.
But here are some information below.

1. We know that it is linked to the date of birth. For some reason, the date of birth is displayed, but by re-entering it it solve the problem for the consultation. It's like if the data where not always well copied.
2. If the date of birth is not set, it impacts the rest of the algo as the complain category cannot be selected.
3. We also know that it happens when scanning the code bar to create a new consultation.
4. Here are some fields that have not been populated properly during our tests (impacted fields are random).
- Child gender
- Caregiver gender
- Caregiver relationship
- Owner of primary phone number
- Empty/clear the cache solve the problem

## Expected behavior
Being able to continue the consultation as planned.

**Comment by GregMart1n** [comment]
One of the local IT has been able to reproduce the problem.
It is still pretty random on why it triggers, but once the problem is detected, it is apparently easy to reproduce.
I link 2 pictures and 1 video.

**Comment by quentingirard** [comment]
Thanks for update, I don't have access to your Sharepoint :) 

Could you post the video directly in GitHub ?

**Comment by quentingirard** [comment]
After taking a look at the video, I found where the bug come from 🥳 

When a user tap multiple time on **New case** it reset **Age in days** variables.

**Comment by GregMart1n** [comment]
Salut @quentingirard , le fix est encore en test sur le terrain, ils ont mis un peu de temps à pouvoir l'installer.
So far so good. Je vais donc clore, et si vraiment on re-ouvrira.

**Comment by GregMart1n** [comment]
The bug is back with the exact same behavior.

App version : 1.2.2
Version id : 85
Build version : 11

**Comment by GregMart1n** [comment]
I imagine it's related, but despite the blank consultation fixed, now it seems that we have partial consultations.

It happens when a new case is created for an existing patient that was present before an app update.

1. So you create a patient, create a close a case.
2. Then update from a reader version to another.
3. Create a new case for this patient, no need to double click on new case, and not all the fileds appears in the consulation.

**Comment by quentingirard** [comment]
Could you provide more information like
- App version change (from - to)
- client-server or in standalone
- Is it the same version used for the first consultation and the next one ?

**Comment by GregMart1n** [comment]
Breaking news form the field ! Always wanted to say that...
The issue is not ! It is apparently the way it was tested, so the short algo they were seeing is actually correct.

**Comment by quentingirard** [comment]
🥳
