### ISSUE TITLE
Red screen for returning patient (PH#3642)

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#520]
## Environment
Happens on test, PROD, control, intervention, different algorithms.

## Describe the bug
After clicking a patient with a closed case, the screen turns red. I have a specific algo that does it.
https://medalcreator.unisante.ch/algorithms/40/versions/73

## To Reproduce
1. Create a patient
2. Create a new case
3. Close the case
4. Select the patient
5. Red screen...

https://user-images.githubusercontent.com/109588388/191478546-bc6afdc1-3f69-43d0-ac24-7195a86ad242.mp4

**Comment by GregMart1n** [comment]
> Could you provide me the device id please ?

1809

**Comment by quentingirard** [comment]
There is a wrong configuration of the algorithm. 

**Kind of consultation** is set in algorithm config but not in registration ordering

Patient profile try to display the value of **Kind of consultation** but there is no answer for it.

Checkout the algorithm config or with @ManuBarchich

**Comment by GregMart1n** [comment]
Case closed !
Thanks

J'ai pu modifié l'algo ;)
