### ISSUE TITLE
Red screen when adding a new patient

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#521]
## Environment
Device ID : 1817
App version : 1.1.6
Algo on data prod : http://195.15.219.241/
![image](https://user-images.githubusercontent.com/109588388/193534227-0646b31e-51fb-4b5f-9a49-0b0016ae328c.png)

## Describe the bug
Add click on "New patient" a red screen is displayed with the error "AN ERROR OCCURED"

**Comment by quentingirard** [comment]
After investigation, it seems data doesn't fetch the latest version of this version of algorithm. I get on reader `json_version: 32` instead of `json_version: 39` present in medAl-creator.

Could you check with the data team ?

**Comment by GregMart1n** [comment]
> After investigation, it seems data doesn't fetch the latest version of this version of algorithm. I get on reader `json_version: 32` instead of `json_version: 39` present in medAl-creator.
> 
> Could you check with the data team ?

So we indeed had a version discrepancy that know has been corrected. `json_version: 34` is the one. 39 is the one from the copy. But I still have a red screen when I click on New patient.

**Comment by quentingirard** [comment]
Bug in date picker. Fixed with attached PR

**Comment by GregMart1n** [comment]
Tested
