### ISSUE TITLE
[Algo switch] problem with patients

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#526]
## Environment
APK : 1.1.7
Algo : Anciennement ePOCT+_DYN_TZ_Control Arm changé en ePOCT+_DYN_TZ_V2.1 (version_id 58)
hf info :
mode : Client serveur
group_id : 315
device_id : 1767

## Describe the bug
When switching from a algo to another (control to intervention), the patient list is displayed, but not all are usable as show on the video. In that example, the 2 firsts are not usable, the ones after are.

## To Reproduce
1. Clear the storage
2. Login to trigger the sync of the new algo
3. Follow steps on video

https://user-images.githubusercontent.com/109588388/197975818-04f2fc55-f906-45a7-9b88-1b307f90b1f3.mp4

**Comment by quentingirard** [comment]
Probably link to https://github.com/Wavemind/liwi-medal-reader/issues/516

The consultation isn't loaded yet, but the bottom nav bar is already good. I will check for a UI improvement.
