### ISSUE TITLE
Change of the "Consent" question

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#528]
## Expected behavior
Change the question to : Oral consent given to use the data for resarch purposes
Change the answer to : yes/no
Remove the document scan as it will only be an oral consent.

**Comment by quentingirard** [comment]
Please refer to https://www.notion.so/wavemindsarl/FOR-ESTIMATION-Modification-du-consent-management-81d7c03135d3480d99d3eba47deba0ef
