### ISSUE TITLE
Diagram picture is missing in Final Diagnose

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#539]
## Environment

Server : http://195.15.219.241/
Version ID : 85
Device ID : 1810
App version : 1.2.2

## Describe the bug
When clicking on information [i] the text is displayed but the diagram is missing.
You can try on _bacterial pneumonia_ and _fever without source_

This algo version is a recent copy.

## To Reproduce
See the video

https://user-images.githubusercontent.com/109588388/208928455-d34408a7-2596-455b-9c3b-99405afde03c.mp4

**Comment by quentingirard** [comment]
The final diagnose doesn't have any media.

https://medalcreator.unisante.ch/algorithms/45/versions/85/diagnoses/7288/final_diagnoses/36681/edit?source=version

It seems to be a duplication issue
