### ISSUE TITLE
Field "sex" not retrieved when a new case (for an existing patient) is generated (PH#3806)

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#543]
## Description of the bug
Medal-reader 1.2.3.
Medal-creator ePOCT_DYN_TZ_3.2 and ePOCT_DYN_TZ_3.3
 
Problem occuring only in client-server mode (not in standalone mode)

Tested on our lab, see the video.

https://user-images.githubusercontent.com/109588388/214534049-4ab39b0a-d9ef-418f-8fbe-69d491208554.mp4

**Comment by quentingirard** [comment]
Seem's probably a miss configuration of the **sex** or **gender** question in medal-creator.

https://medalcreator.unisante.ch/algorithms/48/questions/39965/edit

**Comment by GregMart1n** [comment]
After some testings, it appears that the problem is only in a client-server mode.

**Comment by GregMart1n** [comment]
@quentingirard Have you been able to find anything on this ?
