### ISSUE TITLE
BD5 age in days field management

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#556]
## Describe the bug
We have ~1900 cases where BD5 age in days is not set.
So we would like to understand how this field is managed.
What are the conditions for this field to be set.

When does this field has a value ?
When does this field has NO value ?

**Comment by quentingirard** [comment]
Age in days is a formula variable, based on date of birth question. If date of birth is set, BD5 "Age in days" should be filled with calculated value based on date of birth question.

Do these cases have a date of birth set ?
