### ISSUE TITLE
Display BMI in the reader

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#562]
## Expected behavior
We would like to be able to diplay the BMI in the reader, the same the z-score is.
So after having filled out "Height" and "Weight".

**Comment by quentingirard** [comment]
Here you go

https://www.notion.so/wavemindsarl/3da4b5a17e854d21b3cb3c7d76c99cb5?v=2212c01f84e84b35b306a44195770d59&p=8ded754d595d46ea9d53287874ebf29c&pm=s

**Comment by GregMart1n** [comment]
Offer validated

**Comment by GregMart1n** [comment]
Should be available for TZ and RW, with an option to display it or not.

**Comment by GregMart1n** [comment]
> 

So let's go without this option of hide/display.

**Comment by quentingirard** [comment]
Done the 22.09.2023
