### ISSUE TITLE
Drugs exclusion not working anymore

### ISSUE THREAD

**Issue by GregMart1n** [Wavemind/liwi-medal-reader#563]
## Environment

Server : PROD
Version ID or medAl-Creator URL: The last one

## Describe the bug
The drug exclusion is not working anymore.
Which is a big safety issue

## To Reproduce

VIDEO

https://github.com/Wavemind/liwi-medal-reader/assets/109588388/3935eba7-511c-492f-8308-2235ca638c7c

## Expected behavior
The drug exclusion should work as expectet in the algo config.
Currentl everything is displayed.

## Medical Case Info (if applicable)
Link to diagram:

TZ
https://medalcreator.unisante.ch/algorithms/1/versions/58
https://medalcreator.unisante.ch/algorithms/49/versions/92
https://medalcreator.unisante.ch/algorithms/49/versions/94

RW
https://medalcreator.unisante.ch/algorithms/6/versions/91

**Comment by quentingirard** [comment]
Movie use https://medalcreator.unisante.ch/algorithms/1/versions/58

**Comment by quentingirard** [comment]
After investigation and tests. We cannot reproduce non drug exclusions.

## Use case
MedAL-data url: http://195.15.219.241/
HF: Wavemind
Device id: 1335

MedAL-creator url: https://medalcreator.unisante.ch
Algorithm: https://medalcreator.unisante.ch/algorithms/1
Version: https://medalcreator.unisante.ch/algorithms/1/versions/58

We add in additional diagnoses **Bacterial pneumonia** and **Very low weight for age**. **Amoxicilin HD po** from **Bacterial pneumonia** exclude correctly **Amoxicillin po** from **Very low weight for age**.

![Screenshot_20230908-105922](https://github.com/Wavemind/liwi-medal-reader/assets/15869493/bac379df-001c-4028-9d10-03e0ff2f725d)
![Screenshot_20230908-105934](https://github.com/Wavemind/liwi-medal-reader/assets/15869493/249d88ef-12b3-4554-880a-458e8353d00f)

## Possible issue
After watching video, we think user forget to **agree** or **disagree** drug to trigger exclusion.

**Comment by GregMart1n** [comment]
false alarm, it is a normal behavior...
