### ISSUE TITLE
Crash in "Registration" step

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#77]
**Environment**
Server : https://liwi.wavelab.top/
HF : CH Dynamic Intervention Standalone test
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0

**Describe the bug**
Crash

**To Reproduce**
1. Enter a "First name"
2. Enter a "Last name"
3. Enter a "Gender"

**Expected behavior**
No crash

**Smartphone**
 - Lenovo
 - Android version 10

**Comment by frescoal** [comment]
Cannot reproduce try with latest APK Version
