### ISSUE TITLE
Assessments that shouldn't appear

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#91]
**Environment**

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

**Describe the bug**
Assessments that shouldn't appear -> appear

**To Reproduce**
1. Go to Assessment
2. See error

**Expected behavior**
- Malaria rapid diagnostic test: shouldn't appear
- Hemoglobin (g/dL): shouldn't appear
- HIV rapid test of child/infant: shouldn't appear (see story #73)
- Microscopy for malarial parasites: shouldn't appear

**Screenshots**
![Screenshot_2021-06-29-11-54-06-771](https://user-images.githubusercontent.com/55558015/123778867-db10ae00-d8d1-11eb-8d72-6f48a5957466.jpeg)

**Medical Case Info**

### Registration
Birth date : 2 May 2010

### Complaint Categories
All no

### Basic Measurements
Wight: 20, Everything else: Not feasible, child doesn't feel hot

### Medial History
Cough: Yes. Difficulty breathing: Yes, Everything else: No, Negative

### Physical Exams
Chest indrawing: Yes, Blood oxygen saturation (%): 89, Visible respatory rate: Visibly normal, Everything else: Absent, No, Not feasible, Empty (when possible)

### Assessments
See error

**Smartphone**
 - Device: Lenovo
 - Android version 10

**Comment by frescoal** [comment]
Hemeglobine doit apparaitre voir https://liwi.wavelab.top/algorithms/1/versions/1/diagnoses/933/diagram
Pour le reste c'est fix dans la pull request #94

**Comment by jouz56k** [comment]
> Hemeglobine doit apparaitre voir https://liwi.wavelab.top/algorithms/1/versions/1/diagnoses/933/diagram
> Pour le reste c'est fix dans la pull request #94

Je confirme l'hémoglobine doit apparaitre, sorry pour le mal entendu

**Comment by jouz56k** [comment]
Malaria rapid diagnostic test still appears
