### ISSUE TITLE
Respiratory rate (breaths/min) doesn't work

### ISSUE THREAD

**Issue by jouz56k** [Wavemind/liwi-medal-reader#96]
**Environment**

Server : https://liwi.wavelab.top/
Algo : ePOCT+ Dynamic Tanzania - ePOCT+_DYN_TZ_V1.0
HF : CH Dynamic Intervention Standalone test

**Describe the bug**
Respiratory rate (breaths/min) doesn't work
Error can be related to Git -> #95, because of **Fast breathing (abosulte cut-offs)** 

**To Reproduce**
1. Go to Physical exam
2. Enter 55 in Respiratory rate (breaths/min)
3. Blood oxygen saturation (%) should appear, but it doesn't -> error

**Medical Case Info**

### Registration
Birth date : 3 May 2019

### Complaint Categories
All no

### Basic Measurements
20kg, child doesn't feel hot, Everything else: no

### Medial History
Cough: Yes, Everything else: No, Negative, Empty (when possible)

### Physical Exams
Respiratory rate (breaths/min) -> 55 -> See error, Blood oxygen saturation doesn't appear

**Smartphone (please complete the following information):**
 - Lenovo
 - Android version 10

**Comment by frescoal** [comment]
Gonna need more details.
What Diagram are you using to tell that Blood oxygen saturation should appear ?
What does " doesn't work" mean ? does it crash ? does it generate an error ? in the input empty ? does the app freeze  ?

**Comment by jouz56k** [comment]
By FAST BREATHING (ABSOLUTE CUT-OFFS) : https://liwi.wavelab.top/questions_sequences/5085/diagram,
BOD = 3 May 2019 = 26 Months, and Respiratory rate (breaths/min) = 55 => FAST BREATHING (ABSOLUTE CUT-OFFS) = YES
By RESPIRATORY DISTRESS : https://liwi.wavelab.top/questions_sequences/58/diagram#,
Blood oxygen saturation (%) should appear.

Moreover, by REACTIVE AIRWAY DISEASE : https://liwi.wavelab.top/algorithms/1/versions/1/diagnoses/4/diagram,
Wheezing should also appear (It doesn't in the new APK).

Meaning of "doesn't work" : Nothing happens when enter 55, no error, no freeze 
Consultation can normaly be pursued, just the questions that should appear doesn't appear

Note : In the old APK Blood oxygen saturation (%) and Wheezing appear correctly
